### ISSUE TITLE
No update found for OC 8.2.11

### ISSUE THREAD

**Issue by azrdev** [nextcloud/updater#102]
I try to update from OC 8.2.11 (current 8.2) to NC. I'm following the (current/updated) instructions from [here](https://nextcloud.com/blog/protect-your-privacy-time-to-upgrade-to-nextcloud-11./#newupdater), i.e.:
* `mkdir updater/ && cd updater/`
* `wget https://github.com/nextcloud/updater/raw/master/updater.phar` (master is 345eaa3 at the moment)
* add `updater.server.url` to config.php as stated
* execute `php updater.phar` which outputs
~~~
Nextcloud Updater - version: v11.0.3RC1-13-gdbaec87 dirty

Current version is 8.2.11.

No update available.

Nothing to do.
~~~

* adding index.php doesn't change the output (`wget https://github.com/nextcloud/updater/raw/master/index.php`)

**Comment by MorrisJobke** [comment]
Could you try following URL: https://updates.nextcloud.com/internal_updater_server/ This is for testing only and it should show you the update. If this is successful we could also roll it out on our normal test server.

This is the checkout of https://github.com/nextcloud/updater_server/pull/50 which works for me here.

**Comment by MorrisJobke** [comment]
> Could you try following URL: https://updates.nextcloud.com/internal_updater_server/ This is for testing only and it should show you the update. If this is successful we could also roll it out on our normal test server.

Everybody else who reads this here: This is an test URL and should not be used for production instances, because the content that is served there is used for testing. Currently it is a safe version that is served there, but this could change in the future.

**Comment by azrdev** [comment]
@MorrisJobke I'm sorry, now I updated manually to NC11. I still have the OC8.2 directory lying around, but probably some stuff is stored in the database which got updated/migrated, right?

**Comment by MorrisJobke** [comment]
If you only start the updater (without the batch option) it checks only the config.php and the version.php - so you should be able to verify without the DB.

**Comment by azrdev** [comment]
@MorrisJobke with the internal url it seems to work as expected:
~~~
$ php updater.phar                                                                 
Nextcloud Updater - version: v11.0.3RC1-13-gdbaec87 dirty

Current version is 8.2.11.

Update to Nextcloud 9.0.57 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-9.0.57.zip

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Enable maintenance mode
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] n
Updater stopped.
~~~

**Comment by MorrisJobke** [comment]
Thanks for testing
