### ISSUE TITLE
Can't update from  11.0.3 (beta) -> 12.0.0 Beta 1

### ISSUE THREAD

**Issue by rigrig** [nextcloud/updater#106]
Nextcloud: 11.0.3 (beta)
PHP: 7.0.18
Apache: 2.4.10

Steps to reproduce:
1\) I load any Nextcloud page while logged in as admin user

2\) I get a notification about a new version being available:
![notification](https://cloud.githubusercontent.com/assets/2941436/25633158/81c72512-2f76-11e7-9df9-f5ee3f1dbb08.png)

3\) I go to the updater section in the admin settings

4\) It shows me there is an update available to 12.0.0 Beta 1:
![admin_updater](https://cloud.githubusercontent.com/assets/2941436/25633172/92fd03d8-2f76-11e7-833c-577ed149b65a.png)

5\) I press the "Open updater" button

Actual result:
6a) The updater tells me there is no update
![updater_app](https://cloud.githubusercontent.com/assets/2941436/25633191/9d2285fe-2f76-11e7-9015-40cb878e39a2.png)

Expected result:
6b) The updater updates Nextcloud

----

https://nextcloud.com/blog/nextcloud-12-beta-introduces-the-next-generation-of-secure-collaboration/ mentions
>We will start a staged roll-out of the beta

Possibly it has something to do with that?

In that case the update is not really available yet, so the notification in 2\) and 4\) should not happen.
(Especially since the notification keeps popping up on every page load, and the only way to check if an update is actually available would be to keep opening the updater app)

**Comment by MorrisJobke** [comment]
> > We will start a staged roll-out of the beta
> Possibly it has something to do with that?

@LukasReschke Usually this should not be a problem.

@rigrig Could you provide the updater.log out of the data dir?

**Comment by rigrig** [comment]
Of course, sorry about forgetting to include it:
```
2017-05-02T23:00:54+0200 GUxO9wMiDt [info] request to updater
2017-05-02T23:00:54+0200 GUxO9wMiDt [info] currentStep()
2017-05-02T23:00:54+0200 GUxO9wMiDt [info] show HTML page
2017-05-02T23:00:54+0200 GUxO9wMiDt [info] current version: 11.0.3 build time: 2017-04-22T06:28:24+00:00 9649661f8fc0220b837975fe8afef5b5f7a964ec
2017-05-02T23:00:54+0200 GUxO9wMiDt [info] getUpdateServerResponse()
2017-05-02T23:00:54+0200 GUxO9wMiDt [info] updaterServer: https://updates.nextcloud.com/updater_server/
2017-05-02T23:00:54+0200 GUxO9wMiDt [info] releaseChannel: beta
2017-05-02T23:00:54+0200 GUxO9wMiDt [info] internal version: 11.0.3.2
2017-05-02T23:00:55+0200 GUxO9wMiDt [info] checkForUpdate() Array
(
)

2017-05-02T23:00:55+0200 GUxO9wMiDt [info] end of checkForUpdate() No update available.
```
And my config.php:
```php
<?php
$CONFIG = array (
  'instanceid' => 'ocaed749a93a',
  'passwordsalt' => '***<removed>***',
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'pgsql',
  'version' => '11.0.3.2',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
  'defaultapp' => 'news',
  'enable_previews' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
    8 => 'OC\\Preview\\Illustrator',
    9 => 'OC\\Preview\\Movie',
    10 => 'OC\\Preview\\MSOffice2003',
    11 => 'OC\\Preview\\MSOffice2007',
    12 => 'OC\\Preview\\MSOfficeDoc',
    13 => 'OC\\Preview\\OpenDocument',
    14 => 'OC\\Preview\\PDF',
    15 => 'OC\\Preview\\Photoshop',
    16 => 'OC\\Preview\\Postscript',
    17 => 'OC\\Preview\\StarOffice',
    18 => 'OC\\Preview\\SVG',
    19 => 'OC\\Preview\\TIFF',
    20 => 'OC\\Preview\\Font',
  ),
  'trusted_domains' => 
  array (
    0 => 'fnp.tubul.net',
    1 => 'public.tubul.net',
    2 => 'tubul.net',
    3 => 'webmail.tubul.net',
    4 => 'cloud.tubul.net',
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'owncloud',
  'dbpassword' => '***<removed>***',
  'secret' => '***<removed>***',
  'forceSSLforSubdomains' => true,
  'mail_from_address' => 'nextcloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'tubul.net',
  'updatechecker' => true,
  'updater.server.url' => 'https://updates.nextcloud.com/updater_server/',
  'updater.release.channel' => 'beta',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/nextcloud/public/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'appstoreenabled' => true,
  'appcodechecker' => false,
  'appstore.experimental.enabled' => true,
  'appstoreurl' => 'https://apps.nextcloud.com/api/v0',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trashbin_retention_obligation' => 'auto',
  'asset-pipeline.enabled' => true,
  'overwrite.cli.url' => 'https://fnp.tubul.net',
  'htaccess.RewriteBase' => '/',
  'updater.secret' => '***<removed>***',
);
```

**Comment by LukasReschke** [comment]
I think that's because of https://github.com/nextcloud/updater_server/blob/c37a5441e05093cc90aac932ddbf3cffa1ee876e/config/config.php#L225-L250, we may need to change the order by listing the 10% first and then the 90% last.

If no installation mtime is sent – which we don't do in the updater itself since we don't have database access – it fallsback to the first definition if I remember that right. Let me do a PR … 😞

**Comment by LukasReschke** [comment]
@MorrisJobke Please give https://github.com/nextcloud/updater_server/pull/54 a try. I also added integration tests for this scenario.
