### ISSUE TITLE
"Start update button" not doing anything on 12.0 beta 1

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/updater#108]
Update from beta 1 to beta 2 using the web interface is stuck on the start screen. Pressing "Start update" doesn't change anything:

<img width="1324" alt="screen shot 2017-05-09 at 14 41 10" src="https://cloud.githubusercontent.com/assets/878997/25851305/90bc71d6-34c5-11e7-9e08-68354892ad11.png">

**Comment by LukasReschke** [comment]
It works when I call `/updater/index.php` directly but when opened via the admin interface it doesn't proceed behind that.

**Comment by LukasReschke** [comment]
I tried to replace `updater/index.php` with the code from stable11 and it still fails on Chrome and Firefox. 

Then I installed 11.0.3 and used the update code from master from https://raw.githubusercontent.com/nextcloud/updater/master/index.php and it worked. So I suspect the breaking change is in core.

**Comment by rullzer** [comment]
does it try to load javascript from the server?

**Comment by LukasReschke** [comment]
Gotcha. I think I know why this happens. Let me think how one could solve that :-/

**Comment by LukasReschke** [comment]
My guess is that https://github.com/nextcloud/server/blob/b9bcc819bdad551000981200d7d8d72f5df70778/apps/updatenotification/js/admin.js#L34 probably calls jQuery's eval which we are blocking… mhm…

**Comment by mightyBroccoli** [comment]
Are there any news? Is it still not possible to use the updater to proceed with the update? 
Is manual update time for this version applicable?

**Comment by mightyBroccoli** [comment]
This Issue persists on beta 2 to beta 3.

**Comment by MorrisJobke** [comment]
We know - fixed with beta 3 onwards :/
