### ISSUE TITLE
Get real-life testing by users

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/updater#11]

**Comment by LukasReschke** [comment]
Asked for help at https://help.nextcloud.com/t/test-our-new-work-in-progress-upgrader-script/1214

**Comment by despens** [comment]
Worked for me.

**Comment by stanelie** [comment]
Did not work for me: see https://github.com/nextcloud/updater/issues/26

**Comment by MorrisJobke** [comment]
> Did not work for me: see #26

Was unrelated to the updater itself.
