### ISSUE TITLE
Updater stuck when updating from Nextcloud 12.0.0 Beta 2 to Beta 3

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/updater#112]
I think I have a similar problem as in https://github.com/nextcloud/updater/issues/103 but open a new issue because I am on the 12 Beta version. No idea how much the updaters differ between those versions.

When trying to update from Beta 2 to Beta 3 the updater is either stuck with initializing or does not respond to pressing that button.

![bildschirmfoto 2017-05-17 um 08 08 30](https://cloud.githubusercontent.com/assets/8535968/26140647/3f868cca-3ad8-11e7-8030-2e0aa6ad467e.png)

PS: I already had that issue when updating from Beta 1 to Beta 2. Then I did the update manually.

**Comment by ho1ger** [comment]
PS: I already had that issue when updating from Beta 1 to Beta 2. Then I did the update manually.

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/server/issues/4782#issuecomment-301913373 for how to fix this or use the CLI based version. This is fixed in beta 3 sorry for the issues.
