### ISSUE TITLE
Nc 12.0.0 with stable channel promoted 12.0.0 update

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/updater#117]
See screenshot, having installed 12.0.0 manually with release channel configured to stable:
![2017-05-22 11_36_10-mozilla firefox](https://cloud.githubusercontent.com/assets/1315170/26301986/1ac84e14-3ee3-11e7-9a3f-90232ae2dc13.png)

Due to this being my production install I didn't try to find out what would happen if I actually git the start update button.

Maybe something for @MorrisJobke :)

**Comment by JSoko** [comment]
> Due to this being my production install I didn't try to find out what would happen if I actually git the start update button.

On my system, it updated to NC 12.0.0.28 (from 12.0.0.27)

**Comment by JSoko** [comment]
... and now it promote 12.0.0.29 from https://download.nextcloud.com/server/prereleases/nextcloud-12.0.0.zip

**Comment by AndyScherzinger** [comment]
I can confirm @JSoko's info.

@MorrisJobke How about the updater shows also the complete version number or puts this info somewhere close to the displayed version, so it doesn't confuse the admin (as in me) when looking at the new version :)

**Comment by JSoko** [comment]
...but shouldn't the updater use 
https://download.nextcloud.com/server/releases/nextcloud-12.0.0.zip
instead of 
https://download.nextcloud.com/server/prereleases/nextcloud-12.0.0.zip
???

**Comment by AndyScherzinger** [comment]
I agree, yes. Having "stable" and "seeing" a prerelease path might be confusing. My guess would be that this is due to the updater not yet officially showing the release (before you switch to beta first, which is a hack/workaround).

**Comment by MorrisJobke** [comment]
> @MorrisJobke How about the updater shows also the complete version number or puts this info somewhere close to the displayed version, so it doesn't confuse the admin (as in me) when looking at the new version :)

We did this concept by usually deliver the RC to beta testers and then maybe use the same zip file or with some minor changes under the same file name but with different patch level version number.

I would not show more details here because it only matters for the RC to final step and in the others is not really needed. :/


> ...but shouldn't the updater use
> https://download.nextcloud.com/server/releases/nextcloud-12.0.0.zip

Yes - I guess @LukasReschke  mixed this a bit up, but I guess he put the same file in releases as in prereleases.

**Comment by MorrisJobke** [comment]
So this is just an issue for this specific update cycle in may. Closing then
