### ISSUE TITLE
Having a backup config file breaks update

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/updater#118]
I backed up my Nextcloud config file by copying it to config.php~

When I went to upgrade from NC 12 Beta 3 to NC 12 final, the backup section of the updater halts, saying that it wasn't able to backup config.php~

When I removed that file, the upgrade went perfectly. I can provide full server specs if needed. (SHort version: Debian 8, Nginx, PHP 5.6.3 FPM)

**Comment by MorrisJobke** [comment]
What were the permissions of that file?

**Comment by Bugsbane** [comment]
Ah, ok. Yeah, I realized that while the original config.php file is owned by my webserver user, I used root to copy it, and the copy was owned by root. So that's reasonable that it wouldn't be able to copy that file.

I wonder if halting the backup and stopping the upgrade is the best approach to this kind of situation though. If files aren't in the data directory and they're not original Nextcloud files, maybe we could just give people the option to skip backing them up, and present a list of all skipped files for investigation later? Alternatively, if the upgrade is being done by occ, maybe we could also let the user enter the password for the file owner to also include that file? Just throwing ideas out there. ;)

**Comment by MorrisJobke** [comment]
> I wonder if halting the backup and stopping the upgrade is the best approach to this kind of situation though. If files aren't in the data directory and they're not original Nextcloud files, maybe we could just give people the option to skip backing them up, and present a list of all skipped files for investigation later? Alternatively, if the upgrade is being done by occ, maybe we could also let the user enter the password for the file owner to also include that file? Just throwing ideas out there. ;)

For the config file that could be fine, but if we can't remove any of the code files then the update makes no sense to update all files except some to the new version, because this will break.

**Comment by MorrisJobke** [comment]
Closing as this seems to be solved.
