### ISSUE TITLE
12.0 release - Start Update Button does not work

### ISSUE THREAD

**Issue by dirigit** [nextcloud/updater#119]
Like being reported multiple times in beta and rc-phase:

Start update button does not work.

It simply does nothing.

Tried automatic update from 11.0.3 to 12 as well as manual download and copy.

Edit:
https://nexctcloud.dom/subdir/js/core/merged-template-prepend.js points to root directory of nextcloud and results in "404 file not found". Couldn't find this file ... still searching (js/core/... there is no directory js in root of nc).

Edit again:
search.js is found but reference error: OCA not defined
Similar with
config.js, de.js, update.js, fileinfo.js, client.js - reference error OC not defined

**Comment by dirigit** [comment]
Ok - could fix it for myself by using .htaccess from backup.

Such files should not be overwritten by update.

**Comment by MorrisJobke** [comment]
cc @LukasReschke about this htaccess overwriting. 

> Like being reported multiple times in beta and rc-phase:
> 
> Start update button does not work.

This was only broken if you have installed anything between 12.0.0 beta 1 and RC 2. All other versions worked.
