### ISSUE TITLE
12.0 release - VERY annoying integrity check

### ISSUE THREAD

**Issue by dirigit** [nextcloud/updater#120]
Even .htaccess, which is a very individual and special file, is checked.

And again: Even files from distribution fail the test.

**Comment by MorrisJobke** [comment]
> And again: Even files from distribution fail the test.

And we still don't understand why distributions adds random files there. :/

cc @LukasReschke for the .htaccess, because that should be fine.

**Comment by dirigit** [comment]
Sorry but, it has been fine with 11.0.3.

**Comment by LukasReschke** [comment]
.htaccess is checked as we perform changes in there every release and we require it to match our current release. This lead to many bugs in the past.

If you have custom changes please perform them in your Apache config or so.
