### ISSUE TITLE
Enhancement: Add option to remove backups from updater (auto/button)

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/updater#123]
The updater creates backups (unzipped) of the old installation in the data dir. If you do not pay attention your harddrive is running full. While this is not a big problem for corporate usage (server with much space) this is problematic for home users (webspace, vserver with limited resources). The updater should offer to delete the backup after everthing worked out or a nice button doing that should be available in the admin menu.

**Comment by exploide** [comment]
Alternatively or additionally, the updater could keep a specific amount of backups (maybe one or two) and delete older ones automatically. This way, the files are kept a probably sufficient amount of time while also avoiding a constantly growing collection of backups.

**Comment by MorrisJobke** [comment]
Done in the server with Nextcloud 14+. https://github.com/nextcloud/server/pull/9855
