### ISSUE TITLE
Wrong error message when upgrading from an unknown Owncloud version

### ISSUE THREAD

**Issue by llucax** [nextcloud/updater#125]
I'm trying to upgrade my Owncloud 9.1.6 (9.1.6.2) and I'm getting a weird error at the `Extracting` stage:
```
Downloaded version is lower than installed version
```

After a retry, the error gets even weirder:
```
Cant handle ZIP file. Error code is: 28
```

Searching for the problem, I came across [this post](https://help.nextcloud.com/t/migration-from-owncloud-9-1-6-to-nextcloud-10-0-5-fails/13523/3), that says that the problem is that Owncloud 9.1.6(.2) is not yet known to the updater and suggest changing `config/config.php` to fake the version and use `9.1.5.2` instead.

I tried that trick but Nextcloud still detected the version as `9.1.6`, so I had to also change the file `version.php` accordingly, and after that I could successfully proceed with the upgrade.

I wonder why Nextcloud needs to know about new Owncloud patch-lever versions to work properly, and even then, why the error is so misleading. Maybe at least the error message should be improved.

**Comment by MorrisJobke** [comment]
> I wonder why Nextcloud needs to know about new Owncloud patch-lever versions to work properly, and even then, why the error is so misleading. Maybe at least the error message should be improved.

Because internally a Nextcloud 10 is also a 9.1.x ... To which Nextcloud version did it update? Best would be a 11 version, right @LukasReschke ?

**Comment by llucax** [comment]
To 10, then I did another upgrade to 11.

**Comment by LukasReschke** [comment]
The configuration for the Nextcloud Updater won't work for ownCloud. Make sure to use the code from https://github.com/nextcloud/owncloud-web-migrator which will work with ownCloud.

**Comment by leandro-lucarella-sociomantic** [comment]
I followed the steps in the docs on how to migrate from owncloud to nextcloud.
