### ISSUE TITLE
 Upgrade from nextcloud 10 to version 11 remained to version 10 support

### ISSUE THREAD

**Issue by jimbowarrior** [nextcloud/updater#126]
Hello,

I upgrade owncloud 9 to nextcloud 10 with updater script. I put index.php into updater folder.
Everything works fine except next uopdate to version 11. I get a notification to update to version 11 but when Nexclout check the update he want migrate from Nextcloud 10.0.5 to 10.0.5 version :scream:

Because of index.php move before the first update ?
Why can I update ?

Thanks

**Comment by MorrisJobke** [comment]
Could you please ask in the forums for help? Thanks

https://help.nextcloud.com/
