### ISSUE TITLE
Allow third party apps in "apps2" directory

### ISSUE THREAD

**Issue by schuerg** [nextcloud/updater#127]
The [Nextcloud 12 Server Administration Manual](https://docs.nextcloud.com/server/12/admin_manual/installation/apps_management_installation.html#using-custom-app-directories) states, that the directory called `apps2` should be used for custom apps.

But the Nextcloud updater fails, if this directory exists.

> The following extra files have been found:
> apps2

Imo the updater should allow custom apps in the apps2 directory.

**Comment by xraMsamohT** [comment]
Duplicate of #40
