### ISSUE TITLE
Updater error on shared host (need to provide the unhashed value of "updater.secret")

### ISSUE THREAD

**Issue by poVoq** [nextcloud/updater#128]
See:
https://help.nextcloud.com/t/cannot-update-to-login-you-need-to-provide-the-unhashed-value-of-updater-secret-in-your-config-file/8961

Seems to be an error that effects everyone using OVH shared hosting?

I am trying to autoupdate a fresh install from 11.0.0. to 11.0.3.

**Comment by djibux** [comment]
I am also having that issue.  I found a workaround: go to the "file" app, then straight to the updater from the notification.  That works for me, hope that works for you.

My default app is not the "file" app, so that could be the reason.  Also I use encryption.

**Comment by poVoq** [comment]
I manually updated to 12.0 a while ago, and now the automatic update to 12.1 worked, so I guess this issue can be considered solved.
