### ISSUE TITLE
Error "Move new files in place" when update

### ISSUE THREAD

**Issue by Philippe-M** [nextcloud/updater#133]
Hello, i'm update my installation of nextcloud with the web updater and i've this error

![image](https://user-images.githubusercontent.com/4558101/29557490-8ef823c0-8729-11e7-8c38-e3f18e6f1d00.png)

[updater.txt](https://github.com/nextcloud/updater/files/1241437/updater.txt)

With the previous version I did not have any error and using the same method.

```
php -v
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with XCache Optimizer v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Coverager v3.2.0, Copyright (c) 2005-2014, by mOo
```

**Comment by andre-paulo98** [comment]
nextcloud/server#4855
or here: https://github.com/nextcloud/server/issues/4855#issuecomment-301360485
`go to /location/of/the/website/updater on the command line and execute php updater.phar as the web server user (typically prefix this with sudo -u www-data for Ubuntu for example)
open https://example.org/updater/index.php and follow the instructions there`

**Comment by Philippe-M** [comment]
Hello, after go to php updater.phar i'm going to updater/index.php with my navigator. I'm create and add a new updater.secret in config.php and click on login i've this screen

![image](https://user-images.githubusercontent.com/4558101/29738670-d1609726-8a29-11e7-94bf-b61ac5536354.png)

And on the home page i've this message 

![image](https://user-images.githubusercontent.com/4558101/29738676-ee749664-8a29-11e7-9a23-72e814d68010.png)

Maintenance mode.
