### ISSUE TITLE
upgrade from 11.0.3.2 to 11.0.4 fails

### ISSUE THREAD

**Issue by nufer** [nextcloud/updater#134]
if I try to update from 11.0.3 to 11.0.4 i get the error:
`
Exception: Updates between multiple major versions and downgrades are unsupported.
`
![image](https://user-images.githubusercontent.com/6253591/29711831-1c2d8ebe-8997-11e7-9c93-5fc2733668e8.png)

i'm using docker:
`
docker run -d --restart=always \
    -v /volume1/docker/nextCloud/apps:/var/www/html/apps \
    -v /volume1/docker/nextCloud/config:/var/www/html/config \
    -v /volume1/nextCloud/data:/var/www/html/data \
    -p 33002:80 \
	--name nextCloud \
    nextcloud:11.0.3
`

**Comment by MorrisJobke** [comment]
This is an issue of the server itself. But as this looks quite setup specific I would ask you to seek for help in the forums first: https://help.nextcloud.com
