### ISSUE TITLE
Error extracting zip file

### ISSUE THREAD

**Issue by tflidd** [nextcloud/updater#135]
We have some reports where the extraction of the zip file fails.
https://help.nextcloud.com/t/updating-nc-11-0-2-to-11-0-3-fails-at-extracting-zip-error-code-5/12201
https://help.nextcloud.com/t/help-needed-migration-problem-owncloud-9-1-6-to-nextcloud-10-0-5-extracting-cant-handle-zip-file-error-code-is-5-installation/20188

Can you say why it fails? Is the zip extension too old? If yes we could check for such things and then redirect users to the manual on how to run a manual upgrade.

**Comment by scheinercc** [comment]
Update to the the second link:
I uploaded this php info, which might help shed more light: http://scheiner.cc/info.php

**Comment by nephilim75** [comment]
I am facing same issue while trying to update from 11.0.4 to 12.0.5.

![grafik](https://user-images.githubusercontent.com/19992865/36963087-34c30cea-2052-11e8-8784-2701bd84dbf4.png)

**Comment by Olangu** [comment]
I'm facing the same issue.
I'm on 64-bit Debian Stretch, tried everything...
Would be really nice if the updater would accept a manual directory to read extracted files from.

**Comment by Crell** [comment]
I am getting this error as well.  Trying to migrate from ownCloud 9.1.6.2 to Nextcloud 10.0.6 using the automated upgrader.  First it objects to my version and says it can't downgrade from 9.1.6.2 to 9.1.5.2 (which makes no sense at all).  If I hack version.php to pretend it's 9.1.5.2, I get the ZIP file error.  The only difference is my error code is 28.  

I have no idea what 5 or 28 mean here...

**Comment by trasba** [comment]
Getting the same error while trying to upgrade nextcloud 13.0.1 -> 14.0.1
Are there any requirements regarding installed zip application on the server?
Error is:
> Extracting
Cant handle ZIP file. Error code is: 28

**Comment by karlp** [comment]
Me too, getting this with 13.0.5 to 14.06.  No idea how to restart it cleanly.  (error code 28)

**Comment by Olangu** [comment]
This bug is very strange. Anyone care to comment on the information below?

My debug php-script is here:
[nextcloud_zipError_5_debug.php.txt](https://github.com/nextcloud/updater/files/2757225/nextcloud_zipError_5_debug.php.txt)

If I run the script in my updater directory it fails with error 5.
I try move the zip-file up a directory. Try there, same error.

I move the file to /tmp, and try in that location. Somehow it now works.

I move the zip back to updater directory, and it still works.

I rerun the updater and it finishes the update...


What kind of permission or messed up state can cause this? There's no problem to extract the file with command line unzip with the same user while the script fails.

**Comment by janvlug** [comment]
I ran today into this issue. It actually happened after I had to retry several previous steps as well because they failed, but that succeeded after the retry.

This is some logging from my updater.log:

```
2019-07-14T13:59:52+0200 idd3ZiCrEa [info] end of extractDownload()
2019-07-14T13:59:52+0200 idd3ZiCrEa [info] endStep("6")
2019-07-14T14:00:59+0200 GkPd09UtAg [info] request to updater
2019-07-14T14:00:59+0200 GkPd09UtAg [info] currentStep()
2019-07-14T14:00:59+0200 GkPd09UtAg [info] Step 6 is in state "end".
2019-07-14T14:00:59+0200 GkPd09UtAg [info] POST request for step "6"
2019-07-14T14:00:59+0200 GkPd09UtAg [info] startStep("6")
2019-07-14T14:00:59+0200 GkPd09UtAg [info] extractDownload()
2019-07-14T14:00:59+0200 GkPd09UtAg [info] storage location: /volume1/owncloud/updater-oc00qcm0h0mx/downloads/
2019-07-14T14:00:59+0200 GkPd09UtAg [error] POST request failed with other exception
2019-07-14T14:00:59+0200 GkPd09UtAg [error] Exception: Exception
Message: Can't handle ZIP file. Error code is: 28
Code:0
Trace:
#0 /volume1/web/nextcloud/updater/index.php(1328): Updater->extractDownload()
#1 {main}
File:/volume1/web/nextcloud/updater/index.php
Line:790

2019-07-14T14:00:59+0200 GkPd09UtAg [info] rollbackChanges("6")
2019-07-14T14:00:59+0200 GkPd09UtAg [info] unlink .step
2019-07-14T14:00:59+0200 GkPd09UtAg [info] end of  rollbackChanges()
```

**Comment by janvlug** [comment]
Interestingly enough, it looks like that the archive has already been extracted:

```
root@chaos:~# ls -sla /volume1/owncloud/updater-oc00qcm0h0mx/downloads/
total 12
4 drwxr-x---  3 http http 4096 Jul 14 13:59 .
4 drwxr-xr-x  4 http http 4096 Jul 14 14:09 ..
4 drwxr-xr-x 14 http http 4096 Jul 14 13:59 nextcloud
root@chaos:~# ls -sla /volume1/owncloud/updater-oc00qcm0h0mx/downloads/nextcloud/
total 160
 4 drwxr-xr-x 14 http http  4096 Jul 14 13:59 .
 4 drwxr-x---  3 http http  4096 Jul 14 13:59 ..
 4 drwxr-xr-x 32 http http  4096 Jul 14 13:59 3rdparty
 4 drwxr-xr-x 38 http http  4096 Jul 14 13:59 apps
12 -rw-r--r--  1 http http 12063 Jul 14 13:58 AUTHORS
 4 drwxr-xr-x  2 http http  4096 Jul 14 13:58 config
 4 -rw-r--r--  1 http http  3650 Jul 14 13:58 console.php
36 -rw-r--r--  1 http http 34520 Jul 14 13:58 COPYING
 4 drwxr-xr-x 19 http http  4096 Jul 14 13:58 core
 8 -rw-r--r--  1 http http  4979 Jul 14 13:59 cron.php
 4 -rw-r--r--  1 http http  2836 Jul 14 13:58 .htaccess
 4 -rw-r--r--  1 http http   156 Jul 14 13:59 index.html
 4 -rw-r--r--  1 http http  3172 Jul 14 13:58 index.php
 4 drwxr-xr-x  6 http http  4096 Jul 14 13:58 lib
 4 -rw-r--r--  1 http http   283 Jul 14 13:58 occ
 4 drwxr-xr-x  2 http http  4096 Jul 14 13:59 ocm-provider
 4 drwxr-xr-x  2 http http  4096 Jul 14 13:58 ocs
 4 drwxr-xr-x  2 http http  4096 Jul 14 13:58 ocs-provider
 4 -rw-r--r--  1 http http  2951 Jul 14 13:59 public.php
 8 -rw-r--r--  1 http http  5139 Jul 14 13:58 remote.php
 4 drwxr-xr-x  4 http http  4096 Jul 14 13:59 resources
 4 -rw-r--r--  1 http http    26 Jul 14 13:58 robots.txt
 4 drwxr-xr-x 12 http http  4096 Jul 14 13:58 settings
 4 -rw-r--r--  1 http http  2232 Jul 14 13:58 status.php
 4 drwxr-xr-x  3 http http  4096 Jul 14 13:58 themes
 4 drwxr-xr-x  2 http http  4096 Jul 14 13:58 updater
 4 -rw-r--r--  1 http http   163 Jul 14 13:58 .user.ini
 4 -rw-r--r--  1 http http   364 Jul 14 13:58 version.php

```

**Comment by Git-Me-Some-Hub** [comment]
I am getting the same error in my migration from 16.0.4 > 17.0.1. The Files are extracted, I will sat I have a different mnt location if that matters? /mnt/nextcloud/data/updater-****/downloads

Would love to know why this does not work as it seems to an outstanding issue.

**Comment by nunesgh** [comment]
Same error here. Trying to update from Nextcloud 16.0.7 to 17.0.2.

**Comment by crobarcro** [comment]
Same issue here:
![image](https://user-images.githubusercontent.com/3159692/71972050-d353da00-3203-11ea-9b70-899c9e28c5f5.png)

**Comment by crobarcro** [comment]
Note that the command line upgrade path results in the same error for me:

```
$ sudo -u www-data php updater.phar
Nextcloud Updater - version: v15.0.7-4-ged74b90

Current version is 15.0.11.

Update to Nextcloud 15.0.14 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-15.0.14.zip

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✘] Extracting failed
Can't handle ZIP file. Error code is: 5

Update failed. To resume or retry just execute the updater again.

```

Trying it again gives the same error.

**Comment by crobarcro** [comment]
I wonder if this is a php timeout issue? See here for example:

https://stackoverflow.com/questions/29513245/php-ziparchive-timeout

My server is a raspberry pi 3, and it does take quite a long time to unzip the file.

How could I test this/work around it?

**Comment by crobarcro** [comment]
I tried changing `max_execution_time` from 30 to 120 in both `/etc/php/7.0/cli/php.ini` and `/etc/php/7.0/apache2/php.ini`. I then ran

`sudo service apache2 restart`

but it had no effect.

**Comment by crobarcro** [comment]
I also tried changing `memory_limit` from `128M` to `512M`, and then `-1` in `/etc/php/7.0/apache2/php.ini`, restarting apache after each change and rerunning the updater. Some sites I came across indicated this might help, but didn't help at all either.

**Comment by bitsim-ab** [comment]
> I wonder if this is a php timeout issue? See here for example:
> 
> https://stackoverflow.com/questions/29513245/php-ziparchive-timeout
> 
> My server is a raspberry pi 3, and it does take quite a long time to unzip the file.
> 
> How could I test this/work around it?

See my  quoted comment below for a work around.
Basically you move the file around until it starts working. And then move it back and cross your fingers. It's messed up.
But it's not memory or execution time, it's permissions.

> This bug is very strange. Anyone care to comment on the information below?
> 
> My debug php-script is here:
> [nextcloud_zipError_5_debug.php.txt](https://github.com/nextcloud/updater/files/2757225/nextcloud_zipError_5_debug.php.txt)
> 
> If I run the script in my updater directory it fails with error 5.
> I try move the zip-file up a directory. Try there, same error.
> 
> I move the file to /tmp, and try in that location. Somehow it now works.
> 
> I move the zip back to updater directory, and it still works.
> 
> I rerun the updater and it finishes the update...
> 
> What kind of permission or messed up state can cause this? There's no problem to extract the file with command line unzip with the same user while the script fails.

**Comment by crobarcro** [comment]
I tried what you [suggested](https://github.com/nextcloud/updater/issues/135#issuecomment-572021285) @bitsim-ab. I put your script in the pi user home directory.  In my case:

I run the script in my updater/downloads directory like this:

`sudo -u www-data php /home/pi/nextcloud_zipError_5_debug.php`

it fails with error 5.

I tried moving the zip-file up a directory. Try there, same error.

I move the file to `/tmp`, and try in that location. It now works!

I move the zip back to updater directory, and it still **doesn't** work unfortunately :-(

**Comment by crobarcro** [comment]
Regarding permissions, this is what I have:
```

root@ed-nh-pi01:/opt/nextcloud-data/updater-ocgcv9nemegb/downloads# ls -l ..
total 8
drwxr-x--- 4 www-data www-data 4096 Sep  5 21:41 backups
drwxr-x--- 2 www-data www-data 4096 Jan  8 12:39 downloads
root@ed-nh-pi01:/opt/nextcloud-data/updater-ocgcv9nemegb/downloads# ls -l .
total 72552
-rw-r--r-- 1 www-data www-data 74289159 Jan  8 12:28 nextcloud-15.0.14.zip
```

**Comment by sakuraiyuta** [comment]
I have had the same problem for a long time.

What I have found is that this is a problem specific to Raspberry pi.
I've been running in multiple environments and have never encountered the same problem in a normal x86 environment .

So far, I've had the same problem with Raspberry pi 3B and 4 (memory 4G model). It is occurring.
In both environments, the upgrade from the web fails.

On RPi4, the upgrade from the CLI worked successfully with the following commands.
(18.0.4 -> 18.0.6)

```bash
sudo -Es
cd ${NEXTCLOUD_ROOT_DIR} # <- replace with your nextcloud deploied dir
sudo -u www-data php updater/updater.phar
```

This will work in any case.

If my memory serves me correctly, the upgrade failed on the RPi 3B, even with the CLI.
That's why I always ran Manual Upgrade, referring to the [Manual](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html)

I've tuned MySQL, PHP-FPM and nginx many times, but it didn't make much sense.

**Comment by Olangu** [comment]
> I have had the same problem for a long time.
> 
> What I have found is that this is a problem specific to Raspberry pi.
> I've been running in multiple environments and have never encountered the same problem in a normal x86 environment .
> 
> So far, I've had the same problem with Raspberry pi 3B and 4 (memory 4G model).
> In both environments, the upgrade from the web fails.
> 
> On RPi4, the upgrade from the CLI worked successfully with the following commands.
> (18.0.4 -> 18.0.6)
> 
> ```shell
> sudo -Es
> cd ${NEXTCLOUD_ROOT_DIR} # <- replace with your nextcloud deploied dir
> sudo -u www-data php updater/updater.phar
> ```
> 
> If my memory serves me correctly, the upgrade failed on the RPi 3B, even with the CLI.
> That's why I always ran Manual Upgrade, referring to the [Manual](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html)
> 
> This will work in any case.
> 
> I've tuned MySQL, PHP-FPM and nginx many times, but it didn't make much sense.

Are you sure that it is zip error with errorcode 5 that you get?
Your workaround is not supposed to work with the error described in this bug report.

I have the problem on x86...

**Comment by sakuraiyuta** [comment]
@Olangu 

> Are you sure that it is zip error with errorcode 5 that you get?

No doubt about it. I got same error that @crobarcro explained.

> ![image](https://user-images.githubusercontent.com/3159692/71972050-d353da00-3203-11ea-9b70-899c9e28c5f5.png)

> Your workaround is not supposed to work with the error described in this bug report.

Unfortunately I haven't found solution yet for the complete solution.
(why reason the error occurs, too)

> I have the problem on x86...

Oh, that's sad. Maybe my case was lucky.

The other thing I suspected was the PHP version and the zip module.
I tried installing from pecl, etc., but it didn't solve the problem in my environment.

One possible explanation is that the problem may be due to PC performance.
(I hope it isn't)

I think we need more information to find where the error come from.

**Comment by mucke5** [comment]
> Solved by https://help.nextcloud.com/t/updater-app-runs-into-timeout/12891/3 (running the updater.phar from the cli to avoid the timeout)

Perfect solution, worked flawlessly.

**Comment by rdorsch** [comment]
I saw the same issue while upgrading from 18.0.7 to 18.0.8 on an amd64 Debian 10 virtual server.

The workaround proposed in the nextcloud help ticket above (run updater manually)

`sudo -u www-data php /var/www/nextcloud/updater/updater.phar`

worked flawless as well here.

**Comment by auge8472** [comment]
> I saw the same issue while upgrading from 18.0.7 to 18.0.8 on an amd64 Debian 10 virtual server.

Similar problem here. VM with Ubuntu 18.04. I tried to update from 18.0.6 to 18.0.8 (a few weeks ago) and to 18.0.9 today. It failed with error code 28 during unzip process. The upgrade to 18.0.9 in the terminal worked.

**Comment by zeekoe** [comment]
Same here for 18.0.6 to 18.0.10, except error 28. Using the above suggested updater.phar worked flawlessly (actually, I searched explicitly in the docs for a CLI updater before I tried the web updater, now I see it was "hidden" below the web based updater text)
