### ISSUE TITLE
 Updater ui is not responsive 

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/updater#136]
### Steps to reproduce
1. Open the web updater from administration menu on a mobile device
2. Click Update

### Expected behaviour
Updater should be usable from mobile device, left column should disappear or minimize.

### Actual behaviour
The left column covers more than 75% of the screen (see screenshot) in landscape mode.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page) 12.0.1

**Updated from older Nextcloud (12.0.0) :**
![grafik](https://user-images.githubusercontent.com/26707476/29769000-a80707a0-8be8-11e7-9d7f-32222d120a18.png)

Maybe, it is not needed, because of having only one item with no real function.

**Comment by MorrisJobke** [comment]
makes total sense 👍

**Comment by MorrisJobke** [comment]
Fix is in #138
