### ISSUE TITLE
Update 12.0.1 to 12.0.2/3 1und1 hosting fails

### ISSUE THREAD

**Issue by dirigit** [nextcloud/updater#141]
Trying to perform updates mentioned is not possible for multiple reasons:

1. .htaccess is overwritten which causes an error when NC is running in a sub directory ("file not found", 404 - no redirect happens).  RewriteBase is missing. Claiming it's working based on entry in config.php is wrong - it doesn´t work.
2. Updater's password is not accepted in web interface.
3. Button "Aktualisierung starten" does not work - nothing happens.
4. PHP7 (7.0.23) is not available at shell. PHP5.5 or 5.6 is highest version available. Therefore occ does not work.

**Comment by jospoortvliet** [comment]
Please contact 1&1 support for this, we can't help.
