### ISSUE TITLE
Update 12.0.0 -->12.0.3 fails on 1und1 Webhosting

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/updater#143]
My Cloud instance runs on the 1und1 webhosting service!

Initiating the update process was no problem. However arriving at the step Extracting the following error message appeared:

Extracting
Parsing response failed. <!DOCTYPE html> <html> <head> <meta charset="utf-8"> <style type="text/css"> html, body, #partner, iframe { height:100%; width:100%; margin:0; padding:0; border:0; outline:0; font-size:100%; vertical-align:baseline; background:transparent; } body { overflow:hidden; } </style> <meta content="NOW" name="expires"> <meta content="index, follow, all" name="GOOGLEBOT"> <meta content="index, follow, all" name="robots">  <meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" name="viewport"> </head> <body> <div id="partner"></div> <script type="text/javascript"> document.write( '<script type="text/javascript" language="JavaScript"' + 'src="//sedoparking.com/frmpark/' + window.location.host + '/' + '1und1parking6' + '/park.js">' + '<\/script>' ); </script> </body> </html>

Since then, more then 1 Hour the server remains in maintenance mode!

Each update - minor or major - is **ALWAYS** a **MAJOR** headache!

My advice: **NEVER UPDATE** A running NC server! It only gives you a big headache !

Regards, Hitam4450

PHP 5.6

**Comment by LukasReschke** [comment]
> My Cloud instance runs on the 1und1 webhosting service!
>
> Initiating the update process was no problem. However arriving at the step Extracting the following error message appeared:
>
> Extracting
> Parsing response failed. <style type="text/css"> html, body, #partner, iframe { height:100%; width:100%; margin:0; padding:0; border:0; outline:0; font-size:100%; vertical-align:baseline; background:transparent; } body { overflow:hidden; } </style>
>
> <script type="text/javascript"> document.write( '<script type="text/javascript" language="JavaScript"' + 'src="//sedoparking.com/frmpark/' + window.location.host + '/' + '1und1parking6' + '/park.js">' + '</script>' ); </script>

From what I see there's not much we can do here. 1und1 returned for whatever reason the sedoparking.com page for a request to the updater. This seems more like a misconfiguration on the 1und1 server site.

What you could do to debug this is using the network console of your browser to view the sent requests and responses.  At the moment the best means to recover is probably removing `'maintenance' => true` from your config file.

**Comment by hitam4450** [comment]
PHP 5.6..Webserver I do not know...probably apache .....???

**Comment by hitam4450** [comment]
Ok, 'maintenance' => false, recovered from the prevailing situation!

Everything is running fine on 1und1 Webspace!
Many Thanks !

regards, hitam4450

**Comment by hitam4450** [comment]
Reloading the admin page, presing  Updater öffnen results in the following  - pemanent - error message:

![update_nc2](https://user-images.githubusercontent.com/9738727/30693587-8aaae4a6-9ed0-11e7-9ace-e70e2936fc8e.png)
regards, hitam4450

**Comment by hitam4450** [comment]
Still no advice on how to resolve this issue....

**Comment by MorrisJobke** [comment]
> Still no advice on how to resolve this issue....

Delete the `.step` file in `/path/to/datadirectory/updater-INSTANCEID/` and then restart the updater.

**Comment by hitam4450** [comment]
I tried another update resulting in the same error message as above!  **NO SUCCESS**!

**Comment by MorrisJobke** [comment]
@hitam4450 What is in the data/updater.log?

**Comment by hitam4450** [comment]
Enclosed the updater.log

[updater.log](https://github.com/nextcloud/updater/files/1332182/updater.log)

**Comment by methuselah-0** [comment]
I have the same issue. Any updates on this?

**Comment by jospoortvliet** [comment]
Best ask 1&1 support for this. They claim to host Nextcloud so they should support it, or get support for their customers from us.
