### ISSUE TITLE
 Write permissions issue upgrading 11.0.2 to 12.0.3 Raspberry Pi

### ISSUE THREAD

**Issue by DonTV** [nextcloud/updater#148]
Fail upgrading from 11.0.2 to 12.0.3 RPi 2
![errorpermisos](https://user-images.githubusercontent.com/32441696/31059944-4b901cd8-a6e0-11e7-9791-cb109882c894.jpg)

**Comment by MorrisJobke** [comment]
This can be fixed by giving those files the proper permissions so that the webserver user can write to those files and folders.
