### ISSUE TITLE
ACME (LetsEncrypt) vs Update

### ISSUE THREAD

**Issue by zanglerecke** [nextcloud/updater#150]
i just came across this issue, as i want to update my server.

as mentioned in #92 it would be a problem if there are additional directories. 
the ".well-known" folder of the ACME challange for the certificates is not excluded, and as this could be a common problem it should be.

-> therefore a new issue

**Comment by MorrisJobke** [comment]
Just map the .well-known folder within your web server configuration to a different folder on your server. Then this folder does not need to be included within the Nextcloud updater.

**Comment by zanglerecke** [comment]
how do i map a folder? im on a shared hoster and have no access on the web-server-configs.

**Comment by MorrisJobke** [comment]
> how do i map a folder? im on a shared hoster and have no access on the web-server-configs.

Then you could only remove the folder before the update and add it afterwards. We just have this in place, because it caused in the past serious issues and thus we do not allow any other folders/files to be in the nextcloud directory.

**Comment by zanglerecke** [comment]
thats what I'm actually done, but i am maybe not the only one have some trouble to be up to date. thats why I'm  posting that ;) 

A simple exclude of specific folders would work too. 
Sooner or later the folder will be created again, so it will be there and (if so) cause some troubles

**Comment by MorrisJobke** [comment]
It will be ignored in the future: #183
