### ISSUE TITLE
Warn about apps incompatible with new version

### ISSUE THREAD

**Issue by rigrig** [nextcloud/updater#151]
Current situation: 
* Running NC 12 (stable), NC 13 (beta) is available.
* Some installed apps do not support NC 13 (yet), so would be disabled.

-> It would be nice if the updater warned about this.

Manually checking all your apps is tedious and error-prone, and after a major NC upgrade it might be quite a while before all apps support the new version, so you could be stuck with a disabled app for a long time.

Something like
>Version
>
>Nextcloud 12.0.4
>A new version is available: Nextcloud 13.0.0 beta 1 ￼\[Open updater\]
>**Warning: 2 apps are incompatible with Nextcloud 13.0.0 beta 1 and will be disabled:**
> {Fancy collapsed list to save screen space? This might be a long list:}
> * News
> * Two Factor TOTP Provider

Showing the list on the admin page (instead of in the updater) means
1) :+1: Admins can see it without opening the updater
2) :+1: The updater code doesn't need to be able to check the list of apps
3) :-1: If the updater somehow decides to grab a different version you can still lose apps. (But that shouldn't happen anyway.)

(Not sure if this is the right place to open this issue, as the [update notification](https://github.com/nextcloud/server/tree/master/apps/updatenotification) lives in the https://github.com/nextcloud/server repo?)

**Comment by MorrisJobke** [comment]
This was build by @nickvergessen already and is available as an app: https://github.com/nextcloud/caniupdate or https://apps.nextcloud.com/apps/caniupdate

We also plan to bring it directly into the server.

**Comment by MorrisJobke** [comment]
But thanks for the recommendation :)

**Comment by rigrig** [comment]
Great, always nice to find out NC is already better than I thought :-)
