### ISSUE TITLE
Enhacement: download updates before performing the update

### ISSUE THREAD

**Issue by ngleb** [nextcloud/updater#155]
I recently tried using updater for the first time, before that I always manually did the update. And it appears that at the moment when I started the update, there was issues with connecting to AWS resources and all downloads were extremely slow or didn't work at all (it was limited to a couple of ISPs in my region).

Updater needed to download the following files: nextcloud archive, contacts app archive, calendar app archive.

It took more than 3 hours to finish the update and downloading of those packages were happening in the middle of the whole process which I suspect might be dangerous thing. In normal conditions it takes about 10 minutes to perform the update.

I understand that technically this is not a problem of Nextcloud or the updater app but I assume that network problems might occur with everyone.

It would be great if there was an option that will allow to make sure that all packages are present before starting the updater app.

**Comment by MorrisJobke** [comment]
> It took more than 3 hours to finish the update and downloading of those packages were happening in the middle of the whole process which I suspect might be dangerous thing. In normal conditions it takes about 10 minutes to perform the update.

This repo here is only about the updater part, which only downloads the server itself. Here we plan to move the download of the archive out of the "maintenance mode" section to be able to use Nextcloud during the download.


For the apps this is not that easy and needs to be handled by the server itself.

Thanks for the feedback.

**Comment by MorrisJobke** [comment]
> Here we plan to move the download of the archive out of the "maintenance mode" section to be able to use Nextcloud during the download.

It's implemented in the meantime. So closing this here.
