### ISSUE TITLE
updater forces me to update to 13.0 instead of 12.0.5

### ISSUE THREAD

**Issue by tessus** [nextcloud/updater#159]
I'm currently running 12.0.4 and want to update to 12.0.5.

The updater app (web, command line) forces me to update to 13.0. However, I don't feel comfortable to do so yet.

Is there a way to convince the updater to only update within a release?

**Comment by MorrisJobke** [comment]
> Is there a way to convince the updater to only update within a release?

Use the production channel instead of the stable channel. Production channel receives the updates to the next major version a bit later (with the .1 or .2 release - depending on the feedback we get from users).

**Comment by tessus** [comment]
Thank you for the reply.

> Use the production channel instead of the stable channel.

This seems like a valid workaround currently, but it won't help me as soon as the production channel switches as well.

Is there any chance you guys could create a `Release` channel for which the updater only considers the point updates for the installed release?

**Comment by MorrisJobke** [comment]
> Is there any chance you guys could create a Release channel for which the updater only considers the point updates for the installed release?

Could I ask for the use case first to check what we missed here. Usually we try to get instances upgraded as soon as possible and thus provide the somehow delayed production channel. At some point the old releases are EoL and updating then should only be the last resort.

**Comment by tessus** [comment]
I'm often very reluctant to install a new release. The last 2 major .0 releases had a few severe bugs which would have made my nextcloud instance pretty much unusable.

I'm not saying that I do not want to upgrade, but I might want to wait longer than .1 or .2.

It should be my choice, or at least I should have the option to choose. But you basically force people to upgrade, which is not a very good stategy. All I am saying is that you should give people a choice.

I will most likely upgrade to 13.3 or 13.4, but in the meantime I would still like to update my nc 12 to the latest point release, which I cannot do, as soon as the `Production` channel switches over. But this is your decision, not mine, while in a real admin scenario it should be mine.

**Comment by MorrisJobke** [comment]
As this needs to be put into the server I opened a ticket for this: https://github.com/nextcloud/server/issues/8799

**Comment by tessus** [comment]
Thank you.
