### ISSUE TITLE
updater doesn't do anything

### ISSUE THREAD

**Issue by evanrich** [nextcloud/updater#167]
Every time I try to update nextcloud 12->13, 13.0.2->13.0.3, the UI fails due to timeouts making the backup, so I've tried using the updater.phar file, but it never seems to work:
``` 
sudo -u abc php updater.phar
sudo -u abc php updater.phar
Nextcloud Updater - version: v13.0.0-3-g7a1b76d dirty

Current version is 13.0.2.

No update available.

Nothing to do.
```

The UI is telling me that 13.0.3 is available, but it wont update via CLI.

**Comment by evanrich** [comment]
Every time I try to update nextcloud 12->13, 13.0.2->13.0.3, the UI fails due to timeouts making the backup, so I've tried using the updater.phar file, but it never seems to work:

```
root@442af9079778:/config/www/nextcloud/updater$ sudo -u abc /usr/bin/php ./updater.phar
sudo -u abc /usr/bin/php ./updater.phar
root@442af9079778:/config/www/nextcloud/updater$
```

I'm running nextcloud in a docker container, but that shouldn't be an issue.

**Comment by MorrisJobke** [comment]
This is expected. We found a bug in the login flow for a very few use cases, but stopped the updater. We will push an update soon. See https://github.com/nextcloud/server/pull/9802#issuecomment-395780141
