### ISSUE TITLE
Impossible to install point release before major update

### ISSUE THREAD

**Issue by azrdev** [nextcloud/updater#176]
[The docs](https://docs.nextcloud.com/server/13/admin_manual/maintenance/upgrade.html) recommend to install all point releases (even though it's not anymore explicit that one should do so before upgrading to a new major release):

> It is best to keep your Nextcloud server upgraded regularly, and to install all point releases and major releases without skipping any of them, as skipping releases increases the risk of errors.

The updater, however, wants to pull my 12.0.6 directly to 13.0.4 instead of installing 12.0.9 first.

Maybe related to #159 and https://github.com/nextcloud/server/issues/8799

**Comment by MorrisJobke** [comment]
> The updater, however, wants to pull my 12.0.6 directly to 13.0.4 instead of installing 12.0.9 first.

That is totally fine. I guess we need to update the docs. Thanks for the hint.

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/documentation/pull/790
