### ISSUE TITLE
Updater loop - Same version is shown repeatedly

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/updater#177]
Hi

I recently installed a test setup of 13.0.4, set the update channel to "daily" and updated. 

Now the updater keeps telling me that there is a new version. When I click update (or use the command line tool) all tasks appear to be completed already:

<img width="518" alt="bildschirmfoto 2018-07-10 um 20 14 20" src="https://user-images.githubusercontent.com/8535968/42529141-ea5a876a-847d-11e8-8559-89376af2afc4.png">

When clicking "continue" the updater immediately shows...

<img width="558" alt="bildschirmfoto 2018-07-10 um 20 25 14" src="https://user-images.githubusercontent.com/8535968/42529695-76cfe28e-847f-11e8-9237-9491c1acdd0c.png">

... but the update does not complete.

Firstly I wanted to report this issue (albeit I think similar reports float around the web) and secondly ask how to fix this. I already tried the `php updater.phar` resp. `php occ upgrade` as suggested elsewhere but this seems to be really stuck.

**Comment by ho1ger** [comment]
Well, ... `php occ maintenance:repair` did the trick.

**Comment by MorrisJobke** [comment]
This looks like the post-update repair step was not executed properly and thus the `.step` file is still present in the updater directory. And yes calling the repair step by hand obviously triggers this.
