### ISSUE TITLE
Upgrade automation and management

### ISSUE THREAD

**Issue by sushidave** [nextcloud/updater#178]
Automate Nextcloud and app upgrades, similar to WordPress, offering options for:

Auto-Upgrade:
- enable/disable

Release type selector:
- minor/major releases
- apps

Email notification:
- enable/disable
- for available new releases
- after upgrades have been installed
- for failed upgrades fails, stating the reason
- recipient: admin email address (default) or custom email addresses

Backup management:
- max. number of backups to be kept (= auto-delete older backups) *)
- deletion of individual backups *)

*) See these forum posts:
- [https://help.nextcloud.com/t/manage-backups-from-the-updater-app/7672](https://help.nextcloud.com/t/manage-backups-from-the-updater-app/7672)
- [https://help.nextcloud.com/t/updater-delete-old-backups/7617](https://help.nextcloud.com/t/updater-delete-old-backups/7617)
- [https://help.nextcloud.com/t/remove-backups-after-upgrade/27204](https://help.nextcloud.com/t/remove-backups-after-upgrade/27204)

**Comment by MorrisJobke** [comment]
> for available new releases

Already the case in the server itself (see the update notification that is enabled by default) - it has an option to notify people.

> apps updates

Those are fully handled inside the server and we also not plan to add them to the updater, because it should solve one issue very reliable: "update the server" nothing more and nothing less.



> enable/disable

Which is basically an "enable crontab entry or not".

**Comment by fuco809** [comment]
release channels behaviour feature request:

would be nice if also a channel for "patches only" were available for updates.
https://nextcloud.com/release-channels/

sometimes i just want to rollout available patches and not switch for example from 14.0.4 directly to v15.
cause: i had more to test after a bigger release upgrade than just a patch.

**Comment by MorrisJobke** [comment]
> sometimes i just want to rollout available patches and not switch for example from 14.0.4 directly to v15.
> cause: i had more to test after a bigger release upgrade than just a patch.

We fixed that 2 weeks ago. For details see my description of the new behavior in https://github.com/nextcloud/server/issues/8799#issuecomment-463102707 (also the text in the update notification and channel selector was updated with this)

**Comment by MorrisJobke** [comment]
This seems to be working with the `-n` option and can be closed.
