### ISSUE TITLE
After updater is finished, update process must be run again!

### ISSUE THREAD

**Issue by tflidd** [nextcloud/updater#181]
I have seen this on many updates (NC 12), most recently from 14.0.0 beta 1 to 14.0.0 RC1.

Steps:

- start update: `sudo -u www-data php updater/updater.phar`
- Start update? [y/N] `y`
- Should the "occ upgrade" command be executed? [Y/n] `y`
- Keep maintenance mode active? [y/N] `n`

Now if I go to the login page, it says:

> Nextcloud will be updated to version 14.0.0 RC 1

But I don't want to start such procedures via web-interface, so I run `sudo -u www-data php occ upgrade`

Then it checks all apps again (nothing is done because this step was already carried out during update), and then it works. I'm not sure if there is perhaps an additional step on the database or something like that but this step should be integrated in the update procedure.

**Comment by MorrisJobke** [comment]
The problem with this is to be searched in the server mostly (yes could originate in the updater as well, but we are a bit unsure of the reasons). Could we continue it in that ticket: https://github.com/nextcloud/server/issues/10362

The workaround as of now would be:

> run `updater.phar`, but don't let it execute `occ upgrade` itself, but do it manually. Or just run `occ upgrade` again.

That means to answer at your second last step with `n`.
