### ISSUE TITLE
(hosted service) Update stuck on Step 3

### ISSUE THREAD

**Issue by nr458h** [nextcloud/updater#182]
Hi all.

I have a NC Installation on a hosted service with only access to Nextcloud itself.

In the past all updates went fine (from 12 - > 13) but when I tried to update from 13.05 to 14 RC 1 Everything went fine till step 3. Now it always shows 
*Step 3 is currently in process. Please reload this page later.*

Is there any way to restart or aboard the installation through the GUI? Or where can I point the support to solve this problem?

Thanks in advance

**Comment by 23n** [comment]
Via FTP:
Try to delete the .step file located here:
yournextcloud/data/updater-"randomstring"/.step 

"randomstring" is something like nc5kbpv4n4a5 or whatever, added by the updater 
(i.g. ../updater-c5kbpv4n4a5/.step)

**Comment by nr458h** [comment]
Thanks for the hint, worked well!

**Comment by grisu48** [comment]
The same happened to me. I just had to wait a little bit (went for a cup of coffee), restarted the updater and could resume from step 3.

No need to delete the .step file. Still the process was unpleasant: Initially I assumed the installed instance crashed.

**Comment by ossadmirer314** [comment]
Same here: "Step 3 is currently in process. Please reload this page later."
Message remains, this is a bug...
3 times refeshed after some minutes. no effect.
There is no *.step file to delete
see log:
...
2019-03-05T14:56:54+0100 eMcL6sBLCq [info] currentStep()
2019-03-05T14:56:54+0100 eMcL6sBLCq [info] Step 3 is in state "start".
... 
repeating entries

**Comment by ossadmirer314** [comment]
and now found message after found and deleted .step files:

Create backup
Parsing response failed. <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>500 Internal Server Error</title> </head><body> <h1>Internal Server Error</h1> <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p> <p>Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.</p> <p>More information about this error may be available in the server error log.</p> <hr> <address>Apache Server at xxxxxxxxx.de Port 443</address> </body></html>

**Comment by grisu48** [comment]
I had the same issue when upgrading vom 14.0.4 to 15.0.5. For me waiting a little bit longer solved the issue. Was stuck in Step 3, then in frustration I took a cup of coffee, returned quarter hour later, re-opened the updated and I could resume from that point.

**Comment by daniu-de** [comment]
Hi,
I am having that issue on EVERY update of nextcloud - sometimes more than once ...
regards

**Comment by xydac** [comment]
With nginx update config at least below:
proxy_connect_timeout       600;
proxy_send_timeout          600;
proxy_read_timeout          600;
send_timeout                600;

**Comment by towhereur** [comment]
@xydac in case using nginx as proxy of apache server.
In my case, nginx is one-and-only web server and upgrade from 17.0.0.9 to 17.0.2. data folder size is about 50GB.
On updater page, backup took me about 15 min. so 600 is not enough, so I set it to 1200(1000 would be ok I guess).

there are two files to modify. (nginx conf and php.ini)

nano /etc/nginx/conf.d/nextcloud.conf
--------------------------------------------
location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34])\.php(?:$|/) {
   fastcgi_read_timeout 1200;
}
==========================
nano /etc/php/7.2/fpm/php.ini
--------------------------------------------
max_execution_time = 1200
==========================

service nginx restart

#One more thing
if you have .step file in below folder, delete it. nextcloud-<oldversion> folder in backups folder, delete it.
/usr/share/nginx/nextcloud/data/updater-<randomstring>/

Open updater page and run update.
Hope it helps.
