### ISSUE TITLE
How can I disable automatic backup

### ISSUE THREAD

**Issue by mliker** [nextcloud/updater#185]
I am running the nextcloud on openshift and the automated upgrade is not desirable since the update should be performed by pulling the latest docker image instead

**Comment by MorrisJobke** [comment]
> I am running the nextcloud on openshift and the automated upgrade is not desirable since the update should be performed by pulling the latest docker image instead

Then just don't run the updater. The backup is only done in the updater (the tool basically checks permissions, does an backup and replaces old code with new code) and then it uses the upgrade command (this one is provided by the server itself) which does the actual migration. So you only need to replace the docker image and run `occ upgrade` and you are done.

**Comment by mliker** [comment]
Hi, I am not sure I follow you. The upgrade runs on its own, I don’t run it.

Perhaps it is triggered using a cron? If so how can I remove the updater task?

This is the docker image I am using https://hub.docker.com/_/nextcloud/, the FPM version specifically

**Comment by MorrisJobke** [comment]
> Hi, I am not sure I follow you. The upgrade runs on its own, I don’t run it.
> 
> Perhaps it is triggered using a cron? If so how can I remove the updater task?
> 
> This is the docker image I am using https://hub.docker.com/_/nextcloud/, the FPM version specifically

Then please ask in https://github.com/nextcloud/docker for help. I'm not 100 % aware of how it works and it is maintained by people from the community.
