### ISSUE TITLE
Inconsistencies between notification and updater app

### ISSUE THREAD

**Issue by freeeflyer** [nextcloud/updater#186]
Hi everybody! 

As a picture is more clear than any text :
![nextcloud13-14](https://user-images.githubusercontent.com/12149490/45689056-40e18000-bb53-11e8-84f2-6c6fa9d18dc0.PNG)

As for my configuration : 
```
nicolas@morrigan:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
nicolas@morrigan:~$ uname -a
Linux morrigan 4.4.0-127-generic #153~14.04.1-Ubuntu SMP Sat May 19 14:00:15 UTC 2018 i686 i686 i686 GNU/Linux
```

nothing really relevant in the logs..

Ask any question, happy to give more info

**Comment by MorrisJobke** [comment]
Both of them are provided by the `updatenotification` app in the server - could you open this as a ticket over there? https://github.com/nextcloud/server

Thanks
