### ISSUE TITLE
Web updater fails when updating from NC13 → 14 if EPUB reader ist installed

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/updater#187]
The [Ebook reader](https://apps.nextcloud.com/apps/files_reader) can't be installed in version 14 because it is not supported anymore (at the moment).

`occ app:check-code files_reader`
returns 13 errors, last line is "App is not compliant"

Obviously the updater doesn't check that.

[Spreed.ME](https://apps.nextcloud.com/apps/spreedme) can't be installed in version 14 as well.

BTW, here is a list of "not compliant apps":
https://help.nextcloud.com/t/nc-14-0-1-bug-list-deprecated-file-found-app-is-not-compliant/38213

**Comment by MorrisJobke** [comment]
Those apps are then disabled by the migration step in the server. If this is nit the case it is a server bug and should be opened there.

Could you do that? Thanks a lot for your feedback 👍
