### ISSUE TITLE
allow the admin to specify the version it is updating to

### ISSUE THREAD

**Issue by tessus** [nextcloud/updater#189]
It's once again the time where I can't use `updater.phar` to update my `13.0.6` release to `13.0.7`.

Any chance that you could add an option to specify the version you want to update to?

e.g.: `php updater.phar 13.0.7`

**Comment by MorrisJobke** [comment]
We change the updater server so that major updates are only shipped once you are on the latest minor version of a branch. That should solve the issue most people ran into.
