### ISSUE TITLE
Update Canceling

### ISSUE THREAD

**Issue by fabian727** [nextcloud/updater#202]
hi all,

yesterday I updated my nextcloud instance. It failed, caused by the outdated ssl certificate. Then a "redo" button appeared. It would be nice to also have a "cancel" button to return to the settings page. Instead I had to change the url and to get back to update later.

thanks,
Fabian

**Comment by MorrisJobke** [comment]
> It would be nice to also have a "cancel" button to return to the settings page. Instead I had to change the url and to get back to update later.

Press the back button in your browser should bring you there as well. Thus I will close this here.

**Comment by fabian727** [comment]
with this you can also remove the redo button, as the browser will bring me back to the settings page, there I can then restart the update

**Comment by MorrisJobke** [comment]
> with this you can also remove the redo button, as the browser will bring me back to the settings page, there I can then restart the update

Not really, because the redo button is the direct action. If we would remove it, then the user needs to click back and then "Open updater" again. With a "Back" button we would just duplicate the exact same button of a browser.
