### ISSUE TITLE
Allow admin-specified update backup hooks

### ISSUE THREAD

**Issue by strugee** [nextcloud/updater#207]
My understanding is that the "create backup" step in the updater currently just creates a backup of the code. However, since I'm on ZFS, it's actually incredibly cheap for me to just create a snapshot of the entire Nextcloud installation. I might also want to just perform an entire database dump since my db is small.

It would be awesome if I could provide custom commands to hook into this backup step, so that I could perform potentially more expensive backup steps if I so desired.

**Comment by MorrisJobke** [comment]
We really try to keep this as easy and simple as possible to reduce potential breakage. Is there a reason why you can't do those steps before calling the updater?


Something like this:

```
$ zfs snapshot
$ mysqldump
$ php -u www-data php updater.phar -n
```

**Comment by strugee** [comment]
In principle there isn't really a reason I can't do that. Truthfully I usually prefer to update via the web UI and I never thought of running the updater on the command line - that would make it easier since I won't have to context-switch. The main reason I want it integrated into the updater though is that then I can just forget about it and never have to worry that I didn't remember to back up before an upgrade.

I do understand though that the updater is a very sensitive core component so if you want to reject this for adding too much complexity, I totally get it :thumbsup:

**Comment by MorrisJobke** [comment]
> In principle there isn't really a reason I can't do that. Truthfully I usually prefer to update via the web UI and I never thought of running the updater on the command line - that would make it easier since I won't have to context-switch. The main reason I want it integrated into the updater though is that then I can just forget about it and never have to worry that I didn't remember to back up before an upgrade.

The next problem with adding this to the web UI components: timeouts get more likely if a long running job is triggered in the background. Depending on the configuration of your webserver it could also be killed in the middle of the job and thus cause more problems than what it solves.

Thanks for the feedback anyways 👍
