### ISSUE TITLE
Update Error Step3

### ISSUE THREAD

**Issue by ossadmirer314** [nextcloud/updater#208]
Current version is 14.0.6.
Update to Nextcloud 15.0.5 available. (channel: "stable")

Same here: "Step 3 is currently in process. Please reload this page later."
Message remains, this is a bug...
3 times refeshed after some minutes. no effect.
see log:
...
2019-03-05T14:56:54+0100 eMcL6sBLCq [info] currentStep()
2019-03-05T14:56:54+0100 eMcL6sBLCq [info] Step 3 is in state "start".
...
repeating entries

and now found message after found and deleted .step files:

Create backup
Parsing response failed. <title>500 Internal Server Error</title>
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache Server at xxxxxxxxx.de Port 443 

How to proceed?

**Comment by MorrisJobke** [comment]
Could you check your Webservers logs? Because the 500 error indicates that there is more going wrong.

**Comment by ossadmirer314** [comment]
Ahh, sorry, it is a web hoster instance. 
See please german error log, and have in mind, that this partly not to be solved on webhoster space without support of webhoster. So I need to identify, what can be adapted


Sicherheits- & Einrichtungswarnungen

Für die Sicherheit und Geschwindigkeit Deiner Installation ist es von großer Bedeutung, dass sie richtig konfiguriert ist. Um Ihnen hierbei zu helfen werden einige automatische Tests durchgeführt. Weitere Informationen finden Sie im Tipps & Tricks- Abschnitt und in der Dokumentation.
Es gibt einige Fehler bei Ihrer Systemkonfiguration.

    Letzte Cron-Job-Ausführung: Letztes Jahr. Möglicherweise liegt ein Fehler vor. Überprüfe Cron-Job Einstellungen

    PHP hat keine Leserechte auf /dev/urandom wovon aus Sicherheitsgründen höchst abzuraten ist. Weitere Informationen sind in der Dokumentation zu finden.
    Die PHP-Speichergrenze liegt unterhalb des empfohlenen Wertes von 512MB.
    Der "Strict-Transport-Security“-HTTP-Header ist nicht auf mindestens "15552000“ Sekunden eingestellt. Für mehr Sicherheit wird das Aktivieren von HSTS empfohlen, wie es in den Sicherheitshinweisen erläutert ist.

    Ihr Webserver ist nicht richtig konfiguriert um "/.well-known/caldav" aufzulösen. Weitere Informationen hierzu finden Sie in der Dokumentation.
    Ihr Webserver ist nicht richtig konfiguriert um "/.well-known/carddav" aufzulösen. Weitere Informationen hierzu finden Sie in der Dokumentation.
    Es wurde kein PHP-Memory-Cache konfiguriert. Zur Erhöhung der Leistungsfähigkeit kann ein Memory-Cache konfiguriert werden. Weitere Informationen finden Sie in der Dokumentation.
    Der PHP-OPcache ist nicht richtig konfiguriert. Für eine bessere Leistung empfiehlt es sich folgende Einstellungen in der php.ini vorzunehmen:

    opcache.enable=1
    opcache.enable_cli=1
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.memory_consumption=128
    opcache.save_comments=1
    opcache.revalidate_freq=1

    In der Datenbank fehlen einige Indizes. Auf Grund der Tatsache, dass das Hinzufügen von Indizes in großen Tabellen einige Zeit in Anspruch nehmen kann, wurden diese nicht automatisch erzeugt. Durch das Ausführen von "occ db:add-missing-indices" können die fehlenden Indizes manuell hinzugefügt werden, während die Instanz weiter läuft. Nachdem die Indizes hinzugefügt wurden, sind Anfragen auf die Tabellen normalerweise schneller.
        Fehlender Index "share_with_index" in der Tabelle "oc_share".
        Fehlender Index "parent_index" in der Tabelle "oc_share".
        Fehlender Index "fs_mtime" in der Tabelle "oc_filecache".

Bitte überprüfen Sie noch einmal die Installationsanleitungen ↗ und kontrollieren Sie das Protokoll auf mögliche Fehler oder Warnungen.

Überprüfen Sie die Sicherheit Ihrer Nextcloud mit unserem Sicherheits-Scan ↗.
Version

Nextcloud 14.0.6

Eine neue Version ist verfügbar: Nextcloud 15.0.5
Für 1 App steht keine Aktualisierung für diese Version zur Verfügung

**Comment by MorrisJobke** [comment]
> Ahh, sorry, it is a web hoster instance.
> See please german error log, and have in mind, that this partly not to be solved on webhoster space without support of webhoster. So I need to identify, what can be adapted

For this then the forum is best suited. There is a lot of expertise regarding shared hosters and how to get everything smoothly running.

You can find it at https://help.nextcloud.com - please raise your questions there.

**Comment by pafcioooo** [comment]
For anybody searching, there is solution that helped me: https://github.com/nextcloud/nextcloudpi/issues/411#issuecomment-409393252.
