### ISSUE TITLE
Updater is stuck on Step 3 / mod_fcgid Timeout

### ISSUE THREAD

**Issue by stoamandl** [nextcloud/updater#212]
Hi Nextcloud Team,

I know that there are already some entries on this topic. Unfortunately, apparently none that helps to solve the problem.
I had the problem with the update from 15.04 to 15.05.
Problem is actually the FcgidIOTimeout.
For most hosters or Managed servers (Plesk), the default timeout is 45 seconds.
For example, that was not enough for my big backup installation.
In some posts it is recommended to delete the .step file in the Update directory.
Unfortunately, you re-run in this mistake, as long as you do not increase the timeout.
After adjusting the time out in my Plesk installation the backup worked perfectly again.
Here my Apache mod.
`<IfModule mod_fcgid.c> 
FcgidIOTimeout 300 
</IfModule>`
But i have to delete the .step file again.
Here a better error handling should help!

Thanks!
And still love Nextcloud! Great Software!

**Comment by MorrisJobke** [comment]
Hi,

unfortunately there isn't much we can do if the web server is limited that hard. We can't read this timeout nor can we predict how long the backup step can take. So all you could do is to try it and adjust it for your environment. It's highly recommended to use the updater.phar if there are timeouts involved - that's the far more robust way of updating.
