### ISSUE TITLE
Migration from owncloud 10.1.0 to nextcloud 12.0.12 fails

### ISSUE THREAD

**Issue by Vollbaerti** [nextcloud/updater#213]
After deleting a lot of files and directories manually under the point "Delete old files" because the updater can't delete them, the last directory to delete was "/var/www/owncloud/updater/../core". After doing that I get the follwing message: "core/shipped.json is not available"
How can I resolve this error?

**Comment by Vollbaerti** [comment]
The solution for the error within a normal update does not work for me. I am getting an error message when do start the occ upgrade command manually in both directories, owncloud or nextcloud. The new files had been copied to the nextcloud directory.

**Comment by MorrisJobke** [comment]
The updater tries it's best to predict possible failures.



> After deleting a lot of files and directories manually under the point "Delete old files" because the updater can't delete them, the last directory to delete was "/var/www/owncloud/updater/../core". After doing that I get the follwing message: "core/shipped.json is not available"
> How can I resolve this error?

This one is usually executed before the deletion happens and thus the file is still there. If you delete the updaters step file then there is no way out of manually upgrading.


See https://docs.nextcloud.com/server/stable/admin_manual/maintenance/update.html for the full steps for the usage of this tool.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
