### ISSUE TITLE
Can't upgrade using this script on a digital ocean droplet

### ISSUE THREAD

**Issue by rolandixor** [nextcloud/updater#22]
I get an "invalid password" error, even if I generate a new one.

**Comment by LukasReschke** [comment]
Please provide some more reproduction steps on what you have tried.

**Comment by rolandixor** [comment]
Upon further thought I'm going to have to close this as I manually migrated instead.

FWIW - I simply install index.php in /updater and navigated to /updater in the browser, then attempted to use the secret in config.php or one generated from the CMD, but nothing worked.
