### ISSUE TITLE
note what's needed for update to be possible

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/updater#226]
If you're on Nextcloud 15.0.x and your PHP version is not new enough for Nextcloud 16, you never get the notification that Nc 16 is available. While that is sensible, it means users ask us all the time why they don't get that notification. Would be better if we told them why.

**Comment by MorrisJobke** [comment]
I thought I already pushed a PR, but I didn't - here it is: https://github.com/nextcloud/updater_server/pull/229
