### ISSUE TITLE
tempdirectory (and maybe more in config.php defined folders) should be excluded from the check of extra files

### ISSUE THREAD

**Issue by eisenherzz** [nextcloud/updater#227]
**Is your feature request related to a problem? Please describe.**
When updating Nextcloud:
Check for expected files
The following extra files have been found:
tmp
This folder is defined via `'tempdirectory' => '/www/htdocs/cloud/tmp',`

**Describe the solution you'd like**
tempdirectory (and maybe more in config.php defined folders) should be excluded from the check of extra files

**Comment by joshtrichards** [comment]
Duplicate of #113
