### ISSUE TITLE
Updater always fails because of `.rnd` file

### ISSUE THREAD

**Issue by micheal65536** [nextcloud/updater#229]
The built-in updater (that is used from the web browser) always fails because of an extra file `.rnd` that is created directly under the Nextcloud installation directory. I have seen other reports where the "solution" is apparently to remove this file.

However, this is not a solution. I have done this now for every update since 15.0.2. Every time, the file is re-created again. So every time I want to update Nextcloud I have to first log in to the server command line and remove the file before I can run the browser-based updater.

While manually removing the file on a one-off occasion may be a workaround, requiring this for every update somewhat defeats the purpose of the browser-based updater in the first place (specifically, to avoid the need to log in to the server command line). Judging from the various reports of this issue, it seems that this is a recurring issue that has been around for at least a few years yet nothing has been done to fix it.

Although Nextcloud does not create this file itself, it is known to be safe to delete so the Nextcloud updater should either delete or ignore this file. Its presence is not an "integrity error" as it is normal for it to appear in some cases and it should not require a manual workaround for every update.

**Comment by kesselb** [comment]
https://github.com/nextcloud/updater/pull/183/files how to exclude some files from update, backup or cleanup.

**Comment by micheal65536** [comment]
@kesselb Interesting. That should probably be configurable however as the extra files/directories that appear can be quite specific to a particular installation (for example some users have reported issues with having a `lost+found` directory from the EXT filesystem when Nextcloud is installed to the root of its own partition, or extra files required by a web host).

**Comment by MorrisJobke** [comment]
There is a ticket about extra files already: #68 

Thus closing as duplicate.

**Comment by micheal65536** [comment]
Please do not close. No effort at all is being made to resolve this issue and the developers clearly do not care about this "unexpected files" nonsense that more or less breaks the purpose of the browser-based updater in the first place for anyone who is affected by it.

Saying "move the files out of the way and move them back again" is not solution! I am very disappointed that this could be considered an appropriate response and that no further action is being taken. Requiring users to move files around defeats the purpose of the browser-based updater.

**Comment by MorrisJobke** [comment]
> Please do not close. No effort at all is being made to resolve this issue and the developers clearly do not care about this "unexpected files" nonsense that more or less breaks the purpose of the browser-based updater in the first place for anyone who is affected by it.
> 
> Saying "move the files out of the way and move them back again" is not solution! I am very disappointed that this could be considered an appropriate response and that no further action is being taken. Requiring users to move files around defeats the purpose of the browser-based updater.

There is no action being taken, because there were other tasks with higher priorities. We are all just humans with 24h a day and do this in a best effort way. If you are a customer of Nextcloud GmbH please file a ticket via the support system to shift priorities for such tickets.

I'm sorry that this can't be solved faster, but looking at the overall project we are moving forward quite heavily and just have priorities for some reason to not drown in things that would be nice to fix. Also there is always the option to hand in a pull request and we will have a look if this suits our project.

**Comment by MorrisJobke** [comment]
Fixed via #236
