### ISSUE TITLE
Warn if apps are incompatible

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/updater#241]
As caniupdate is now included to web-ui updater, this should also be done updater.phar

**Comment by MorrisJobke** [comment]
> As caniupdate is now included to web-ui updater, this should also be done updater.phar

Unfortunately not going to happen IMO. The caniupdate code is present in the server web UI before the updater itself is started. And I want to avoid to have dependencies on server code. Thus neither the web UI nor the CLI of the updater will get this. The updater itself is just to replace old code with new code.

Sorry for the bad news here.

**Comment by MorrisJobke** [comment]
Maybe we can add this as an occ command that can be executed before on the CLI to check for missing app updates.

**Comment by joshtrichards** [comment]
> Maybe we can add this as an occ command that can be executed before on the CLI to check for missing app updates.

nextcloud/server#34713 is tracking that.

In theory, we could also integrate this into the Updater as a pre-check step and run it in the same  way we do `occ upgrade`.

Also, related #401
