### ISSUE TITLE
updater still shows old versions (no 15.0.12 or 16.0.5)

### ISSUE THREAD

**Issue by tessus** [nextcloud/updater#246]
At one point I was told that downloads are not pushed to the updater for a week, but it's been 9 days, since the new versions were released, but the updater still does not see them.

**Comment by tessus** [comment]
I'm on the production channel using 15.0.11) and it is supposed to tell me that 15.0.12 is available.
After I'll have upgraded to 15.0.12, I will probably pretty soon update to 16.0.5.

**Comment by dn1987p** [comment]
Is it possible to force the updater to update to the same supported major release (so e. g. from 15.0.11 to 15.0.12)? If I tried to update in the past, usually it just wants me to update to the latest major release. For now the updates though still don't show up in production release channel.

Maybe it still gets delayed because the contacts app was broken for 15.0.12...

**Comment by tessus** [comment]
@dn1987p this is exactly what the `production` channel did (after I finnaly convinced the devs that people might not want to upgrade to the next release, when there are still minor updates for the installed release available). It showed the update to the minor update in the current major release and if not available, it showed the upgeade to the next major release.

Frankly this entire channel thing is not really working properly anyway. They forget to update the channels and it's too unflexible.
I want to choose the major release and lock it down to that release. The production channel update was a change in the right direction, but it's currently not working.

**I would like to see an option for the command line updater where I can specify the release (14, 15, 16, 17) and the exact version (16.0.5). Unfortunately no dev has thought about that. If you know the code base, this is a change of a few minutes. All problems solved.**
And for the GUI a setting where I can choose a release (15, 16, 17) and lock it down. Only updates within that release is possible.

I can just hope that one dev decides that he can invest a few minutes and add that.

I suspect that the devs have imagined at the beginning that they will decide when you have to update. Unfortunately they didn't realize that every single major upgrade breaks the nextcloud instance.

**Comment by tessus** [comment]
Dear devs,

I've posted here, because there's no category for the updater on the forum. If you want me to post there, please let me know in which category.

Otherwise, please let me know how I can use the updater to update from 15.0.11 to 15.0.12.

**Comment by TP75** [comment]
> Otherwise, please let me know how I can use the updater to update from 15.0.11 to 15.0.12.

I am not a NC dev but I take the liberty to make you aware of some information.

There is a section in the NC 15 Admin Manual on this topic available: [Upgrade manually](https://docs.nextcloud.com/server/15/admin_manual/maintenance/manual_upgrade.html).
Likewise, the NC 16 Admin Manual on this topic abailable: [Upgrade manually](https://docs.nextcloud.com/server/16/admin_manual/maintenance/manual_upgrade.html)

Please be aware you should be sufficiently familiar with the commandline and the relevant administration tasks to your operating system.  Always start by making a fresh backup and disabling all NC 3rd party apps.

Please heed the requirement the `sudo -u www-data php occ upgrade` command **has to be** executed from _within_ your nextcloud installation directory.

**Comment by tessus** [comment]
@TP75 Thanks for your comment, but I know how to upgrade manually. My point is that the updater is useless, if it only works now and then because of a design flaw. I've been updating manually almost every time, but how great would it be, if there was a tool that did that. Oh wait, there is.

**Comment by TP75** [comment]
Please accept my aplogies for not meeting your expectations.

In general, it would be good to have a more reliable and more flexible GUI updater.  However, one should keep in mind this is the FOSS branch and one should not demand anything for nothing, I presume.

**Comment by tessus** [comment]
> it would be good to have a more reliable and more flexible GUI updater

I'd rather have the script working properly.

> one should not demand anything for nothing,

I'm not demanding anything, but after 6 years or however long the updater has been around, is it too much to ask that one can use the updater to update one's installation? Yes, I can use it to update my installation to whatever somebody else decides, but I can't use it to update to the version I want. Don't you think this is ridiculous?

**Comment by TP75** [comment]
@tessus AFAIK this is the Community Forum and there seem to exist other [options for support](https://nextcloud.com/support/):
> If you run Nextcloud in a mission critical environment with large numbers of users and big amounts of data and need the certainty of support from the experts behind the Nextcloud technology, a [Enterprise Subscription from Nextcloud](https://nextcloud.com/enterprise) is available with email and phone support.

Furthermore, one could change the code locally and/or one could make a contribution to the code base i.e. file a commit to the NC repository at GitHub.

**Comment by tessus** [comment]
@TP75 I reported a bug, but you thought you should reply to a comment that was directed to the devs. I kindly ask you to stop hijacking this issue. Unless you know why the production channel isn't doing what it's supposed to, please stop.

**Comment by tessus** [comment]
Opening issues for Nc is useless.
