### ISSUE TITLE
Error Updater 17.0.0 Extracting Error during unpacking zipfile: No error - and now another Error

### ISSUE THREAD

**Issue by witzker** [nextcloud/updater#248]
![grafik](https://user-images.githubusercontent.com/4120266/66708168-7b185380-ed4c-11e9-9501-1c662df661ad.png)

Problem discribed here:
https://help.nextcloud.com/t/error-updater-7-0-extracting-error-during-unpacking-zipfile-no-error/61865/2

pls give me Info how to solve this

**Comment by witzker** [comment]
No NEWS?

**Comment by witzker** [comment]
another TRY Now THIS
![grafik](https://user-images.githubusercontent.com/4120266/66993063-3cc3c100-f0cb-11e9-9b35-ebe93bbb774e.png)

PLS Help

**Comment by devosthomas** [comment]
same issue with me

**Comment by mathieu-aubin** [comment]
same error here

**Comment by mathieu-aubin** [comment]
Had the same issue, ended up being quota reached from a webmin user

**Comment by Relax-Roger** [comment]
Same happens when I try to update from 16.0.6. to 16.0.7.

**Comment by devosthomas** [comment]
> Had the same issue, ended up being quota reached from a webmin user

Same case with me. Make space :)

**Comment by Relax-Roger** [comment]
> Same case with me. Make space :)

Thanks for the advice! I have deleted some old Nextcloud backup folders from previous updates, _et voilà_ problem solved. 
Those folders keep piling up considerably. I really feel the updater should offer some help on managing/deleting old backups...

**Comment by mathieu-aubin** [comment]
check https://github.com/nextcloud/updater/issues/248#issuecomment-568316672 for a potential fix
