### ISSUE TITLE
Download failed on CURLOPT_FOLLOWLOCATION

### ISSUE THREAD

**Issue by mtraeger** [nextcloud/updater#25]
Trying to upgrade from Nextcloud 9.0.50 with the new updater failed with following message at the download step:
```
Parsing response failed.
Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /www/owncloud/oc6/html/updater/index.php on line 491
{"proceed":true}
```

I fixed this temporarily by commenting `curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);` in line 491.

This might be caused by my settings, an open_basedir is configured.
Ubuntu 16.04
Apache 2.4.7
PHP 5.5.9

One side note: You could think about automatic scrolling to the current active step.

**Comment by MorrisJobke** [comment]
@LukasReschke Should we check for the open_basedir being set and then simply don't send the FOLLOWLOCATION header? The down side would be that it then not works if we redirect the download link and it then is even harder to debug.

Ideas?

**Comment by LukasReschke** [comment]
> The down side would be that it then not works if we redirect the download link and it then is even harder to debug.

I'd say we should completely remove CURLOPT_FOLLOWLOCATION then to make it consistent.
