### ISSUE TITLE
If updated is blocked show the reason

### ISSUE THREAD

**Issue by tflidd** [nextcloud/updater#258]
It seems that there are a few checks implemented, e.g. the php version if it is compatible or not. If there is a conflict with the current environment, the update button is not shown but no information why it isn't shown (or it wasn't obvious to the user):

https://help.nextcloud.com/t/solved-update-upgrade-from-15-to-16-missing-button-link/66225

**Comment by tflidd** [comment]
NC 15 is running out of support, it would be great to get this fixed soon for these people

**Comment by stefan123t** [comment]
I just checked the source code, it must be implemented somewhere in the server under apps/updatenotification/lib/UpdateChecker.php

The model /apps/updatenotification/lib/Settings/Admin.php in the VueJS view /apps/updatenotification/src/components/root.vue calls getUpdateState() to find out what the current state to display should be.

The checks mentioned by @tflidd above are done in /lib/private/Updater/VersionCheck.php

In case of any error this currently just returns false, instead it should throw along an error message to be displayed. Also the code prepares a JSON message with the following information:
		$version = Util::getVersion();
		$version['installed'] = $this->config->getAppValue('core', 'installedat');
		$version['updated'] = $this->config->getAppValue('core', 'lastupdatedat');
		$version['updatechannel'] = \OC_Util::getChannel();
		$version['edition'] = '';
		$version['build'] = \OC_Util::getBuild();
		$version['php_major'] = PHP_MAJOR_VERSION;
		$version['php_minor'] = PHP_MINOR_VERSION;
		$version['php_release'] = PHP_RELEASE_VERSION;
		$versionString = implode('x', $version);

The server at https://updates.nextcloud.com/updater_server/?version={JSON} will respond upon receiving it at its own descretion. I do not know if I am able to debug what the server sends me currently as a response right after the upgrade to 16.0.7, but there seems to be a cache lock of 30 minutes preventing spamming of the NC server.

**Comment by MorrisJobke** [comment]
In the meantime this is solved in the Nextcloud server itself. We now show when the PHP version is out of date and link to a blog post on our website with more details.

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/updater_server/blob/d6062641391513f3757f168ed70c709324da8616/config/config.php#L263
