### ISSUE TITLE
migration from owncloud failed with upgrader script

### ISSUE THREAD

**Issue by stanelie** [nextcloud/updater#26]
Hello.

I just tried to migrate my installation from owncloud 9.0.2 to Nextcloud using the updater script as per https://help.nextcloud.com/t/test-our-new-work-in-progress-upgrader-script/1214 .

The script looks like it worked. However, it failed in the next step trying to upgrade the database with this error:

> 
> Updating Nextcloud to version 9.0.52, this may take a while.
> 
> Preparing update
> Set log level to debug
> Turned on maintenance mode
> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing ' DELETE FROM `oc_lucene_status` WHERE `fileid` IN ( SELECT `fileid` FROM ( SELECT `fileid` FROM `oc_lucene_status` GROUP BY `fileid` HAVING count(`fileid`) > 1 ) AS `mysqlerr1093hack` )': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED.
> The update was unsuccessful. Please report this issue to the Nextcloud community.
> 

I can roll back to a previous snapshot if it helps testing with you guys.

Thoughts?

**Comment by MorrisJobke** [comment]
This is a configuration issue with your database. Please see https://docs.nextcloud.org/server/9/admin_manual/configuration_database/linux_database_configuration.html#mysql-mariadb-with-binary-logging-enabled for details how to fix this.

**Comment by stanelie** [comment]
As an end user just trying to migrate and not aware of this issue, maybe I should get a warning from the updater script that my installation will be trashed and unusable after migrating? Perhaps with some tips as to how I should fix things before trying to run the updater script another time?

**Comment by stanelie** [comment]
For reference and for others who might be having this issue, I fixed it by commenting out these lines in my /etc/mysql/my.cnf file and restarting the mysql service:
```
# log_bin              = /var/log/mysql/mariadb-bin
# log_bin_index        = /var/log/mysql/mariadb-bin.index
# sync_binlog          = 1
# expire_logs_days     = 10
# max_binlog_size      = 100M
```

Thanks for the tip, MorrisJobke

**Comment by MorrisJobke** [comment]
> Perhaps with some tips as to how I should fix things before trying to run the updater script another time?

We try to add  lot of these tips in front of the update, but not all are easily detectable (like this one). So the only way to do this is to document the error message and provide the needed information.

**Comment by stanelie** [comment]
Ok, thanks.
