### ISSUE TITLE
If updater is called with a non-default php binary use it also for ./occ

### ISSUE THREAD

**Issue by intervisionlord** [nextcloud/updater#261]
```
Update of code successful.

Should the "occ upgrade" command be executed? [Y/n] y
This version of Nextcloud requires at least PHP 7.1<br/>You are currently running 7.0.33-0+deb9u6. Please update your PHP version.
Keep maintenance mode active? [y/N] n
This version of Nextcloud requires at least PHP 7.1<br/>You are currently running 7.0.33-0+deb9u6. Please update your PHP version.
Maintenance mode is disabled
[~/www/******] *****@**** > /opt/php73/bin/php -c ../../php-bin-isp-php73/php.ini -i | grep -i 'php version'
PHP Version => 7.3.11
PHP Version => 7.3.11
```

Why so?

**Comment by kesselb** [comment]
`PHP_BINARY` should contain the currently used php binary in a cli environment.

**Comment by intervisionlord** [comment]
Hmm.. i have several versions of PHP on my server for serveral different scripts that's why i try to execute updater with correct version manually

**Comment by kesselb** [comment]
> i have several versions of PHP on my server for serveral different scripts that's why i try to execute updater with correct version manually

That works for the updater itself but not for calling occ from the updater. That's not working. Someone needs to fix it by using `PHP_BINARY` ;)

Workaround:

> Should the "occ upgrade" command be executed? [Y/n]

N

> /opt/php73/bin/php -c ../../php-bin-isp-php73/php.ini occ upgrade

**Comment by intervisionlord** [comment]
> /opt/php73/bin/php -c ../../php-bin-isp-php73/php.ini occ upgrade

it's suitable for me )
