### ISSUE TITLE
Stuck at "Update in process."

### ISSUE THREAD

**Issue by CyberMew** [nextcloud/updater#268]
Tried updating 18.0.0 to 18.0.1 and it failed (some write error).

Then I pressed back and I got this. The whole thing died. How do we recover from this? This is horrible. I can't find a cleanup article on this.

**Comment by Dragon988** [comment]
Never press back during an upgrade process.

If you're lucky the database finished updating and all you need to do is backup the config.php, remove all the old files (NOT the user directory) and replace them with new files and then move the config.php back.

If the database finished that should be all you need to do other then disabling maintenance mode.

If the database finished halfway through you're going to need to manually repair it.

If the database didn't updated at all follow the same process and disable maintenance mode.

Good luck! And if you have any useful information such as errors from the log files post them so the developers here can investigate the issue.

To be fair this also happened to me but my database finished the upgrade process and I was able to fix the installation using the first method I described.

**Comment by joshtrichards** [comment]
Given the write error (and the age of this issue) it's likely not going to be possible to isolate the cause of your particular situation. Hopefully the tips from @SimplyCorbett were hopeful and you got it worked out.

In the future:

- there is a log that may provide clues: `updater.log` (or be helpful for a bug report if there seems to be a bug)
- try posting to the [Nextcloud Help Forum](https://help.nextcloud.com) for general update / recovery / troubleshooting assistance

After making sure you have a backup (a good idea regardless) the manual update approach is sometimes an option:

https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html

But the write error may be a hint that something else was wrong with your environment at the time. So it depends on the specifics of that error.
