### ISSUE TITLE
apt install leftovers

### ISSUE THREAD

**Issue by stanelie** [nextcloud/updater#27]
Hello.

I just migrated from a package installed version of owncloud on Ubuntu.

What should I do with the owncloud, owncloud-files and owncloud-deps-php5 packages? What happens if apt tries to upgrade them on top of NextCloud next time I do a `apt-get upgrade`? If I uninstall them now, will they remove NextCloud files with them? Should I just put a hold on them in apt and forget they even exist at all?

Thanks!

**Comment by MorrisJobke** [comment]
I didn't test this yet. But it is maybe worth a try and then we should document this.

@jospoortvliet Do you have already "how to migrate from ownCloud packages to Nextcloud" on your agenda? Is this wanted?

**Comment by stanelie** [comment]
Removing the **owncloud** and **owncloud-deps-php5** packages had no impact.
Removing **owncloud-files** hosed my installation.

So, I have to leave this package installed, and it is at risk of being upgraded by a `apt-get upgrade` next time owncloud publishes an update.

Until this issue is fixed, I issued a `apt-mark hold owncloud-files` to make sure my nextcloud install doesn't get trashed by a future **owncloud-files** package upgrade.

**Comment by JSoko** [comment]
Hello,

[quote]Removing owncloud-files hosed my installation.[/quote]

I had this problem too...
...after removing owncloud-files 

I just did the Nextcloud manual upgrade with moving everythin to an other folder, restoring /config, /data and /themes and then copying the archive to the new cloudfolder.

**Comment by jospoortvliet** [comment]
I blogged about migration here: http://blog.jospoortvliet.com/2016/06/migrating-to-nextcloud-9.html

but I didn't really address this point. What I personally did is keep the packages but remove the repo so they will remain, forever, unchanging.

**Comment by stanelie** [comment]
Thanks for the tip.
So, I removed the file `/etc/apt/sources.list.d/owncloud.list` and it is not trying to upgrade ownCloud anymore.

Thanks!
