### ISSUE TITLE
New Enhancement for updating

### ISSUE THREAD

**Issue by ddurocher** [nextcloud/updater#273]
When one is updating via the web interface to new version one is forced to go to the config.php and insure that the appstoreenable is set to false.

a simple button there would ensure that the directive is set correctly.

once update is complete a button on the app page to reset the line to true would be very helpful.

this could also be configured to do all that automatically no user intervention required.
most of us use the app store to keep our apps updated if required. 
there is really no reason today to force someone to manually edit a config file for anything.

**Comment by MorrisJobke** [comment]
I don't get why the appstore should be disabled during updates. If disabled then apps are not automatically updated during the update of the server. But this is actually wanted. I don't plan to change the default behavior with the updater. If this is needed then please create a script to do this flip of the appstore flag.
