### ISSUE TITLE
YACUP (Yet Another Can't Update Post)

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/updater#274]
I'm using the linuxserver Nextcloud container and I'm getting stuck here every time.:

![image](https://user-images.githubusercontent.com/39491297/77036195-88311280-697c-11ea-86bb-f9f6206a7ffa.png)

**Comment by kesselb** [comment]
As I explained at most of the other posts. If your web server timeouts not much we can do. Use the CLI to update.
