### ISSUE TITLE
Cannot updade NC from 17.0.1 to 18.0.2 - Destination is not writable

### ISSUE THREAD

**Issue by akurzawa** [nextcloud/updater#275]
Nextcloud from scratch on debian 9.9
nginx version: nginx/1.17.4
installed using c-reiger script

![image](https://user-images.githubusercontent.com/20043789/77250136-23a8d880-6c46-11ea-86e9-f22d22bc8ce4.png)

- no changes on file system/permission after install - I keep this system clean 
- web updater worked well till uptading to version 17.0.1
- while ruinning updates there are no entries in admin/log regarding update process
- no errors in nginx 

Any help appriciated becouse I don't want to stuck to version 17.0.1 due to security

Here is the forum thread:
https://help.nextcloud.com/t/cannot-updade-nc-from-17-0-1-to-18-0-2/74745

**Comment by PVince81** [comment]
I'll close as this issue is old and I'm guessing that you found another way to upgrade

if the problem persists, feel free to reopen
