### ISSUE TITLE
ability to disable backup process within update

### ISSUE THREAD

**Issue by daniu-de** [nextcloud/updater#282]
everytime I update Nextcloud I get problems at the step "backup", Therefore I disable the step in the source code and have no issue updating. The first couple of times I was looking for solutions and found that lots of people have issues like that.

Now I found that this backup also consumes quite some space on my webspace

My provider is doing a perfect backup (database and program data) - better than Nextcloud could do it - rolling back Nextcloud would be way more complicated with the internal method than using my providers backup. In fact I rolled back Nextcloud quite often with my providers backup because the Nextcloud rollback did not work.

PLEASE give us a way to turn off backing up before doing an update - I - and for sure many others don't need it ...

**Comment by johkoenig** [comment]
@daniu-de until this is fixed, could you please tell us which lines have to be removed to skip the backup?

**Comment by MorrisJobke** [comment]
> @daniu-de until this is fixed, could you please tell us which lines have to be removed to skip the backup?

For the web updater: https://github.com/nextcloud/updater/blob/cbf2b53e5e7806a5135b4c1dbe8edbe97e9e78ac/index.php#L1345

**Comment by johkoenig** [comment]
@MorrisJobke thanks!
I'm looking for the same on the command line updater.

As an idea for the command line updater: An option like "--no-backup" would be great!

**Comment by MorrisJobke** [comment]
> @MorrisJobke thanks!
> I'm looking for the same on the command line updater.
> 
> As an idea for the command line updater: An option like "--no-backup" would be great!

cc @kesselb ;)

**Comment by MorrisJobke** [comment]
> As an idea for the command line updater: An option like "--no-backup" would be great!


19.0.4, 18.0.10 and 17.0.10 will contain it. See #292 


I don't plan to add this to the web UI as of now.

**Comment by daniu-de** [comment]
that is not userfriendly at all. Everybody who has a decent backup does NOT NEED that annoying backup that just fills up space on the harddrive. Just forgot to disable the backup again and will spend lots of time deleting it since I do not have proper access to the server and ftp gets disconnected all the time ...

**Comment by Moilleadoir** [comment]
Updates just don’t work without this.

**Comment by william-e** [comment]
Hi Morris,
could you please reconsider, I find it very annoying too ...

**Comment by a-ly** [comment]
I think in modern installations one really does need the ability to disable the backup... Who still uses file systems without snapshots in 2021? A Snapshot takes less than a second, the backup in the update takes forever and is less useful.

**Comment by kesselb** [comment]
> I think in modern installations one really does need the ability to disable the backup... Who still uses file systems without 
snapshots in 2021? A Snapshot takes less than a second, the backup in the update takes forever and is less useful.

You know that the updater has support to skip backup when using on the command line?

**Comment by a-ly** [comment]
> > I think in modern installations one really does need the ability to disable the backup... Who still uses file systems without
> > snapshots in 2021? A Snapshot takes less than a second, the backup in the update takes forever and is less useful.
> 
> @a-ly You know that the updater has support to skip backup on the command line?

@kesselb yes, but not everybody has access to command line, but can take a snapshot. Why not have that option in the web interface?

**Comment by kesselb** [comment]
> Why not have that option in the web interface?

I don't think there is a technically reason to not have such an option in the web based updater. I'm not going to build it as the cli option is good enough for and I don't care much about users without shell access. As you said it's 2021 - who uses a shared hosting without ssh access? ;)

**Comment by jackrsteiner** [comment]
I'm wondering if there's an option that's the inverse of --no-backup? Like, if you don't want updater to run, but just want the updater step 3 to run, is there an occ or updater command for this already? I think this is sort of a necessary compliment to updater --no-backup, even if the operation is trivial.

**Comment by daniu-de** [comment]
I currently don't have access to a shell and since this seems to be so unwanted I keep editing the file updater.php (?) which is much easier than leading that useless discussion here. I don't like the fact that the programmers are so ignorant though ...
Had been thinking about writing some script that does it for me - I could do that - adding the feature is beyond me unfortunately

The point for me (no shell access) is also that it takes ages (I guess half an hour with a good ftp programm is not enough) to delete that space consuming, unnecessary backup since fast commands are not available for me ...

**Comment by linuxmangr** [comment]
> 

Thank you very match, you save my time.
Is very useful  solution/.

**Comment by linuxmangr** [comment]
> > @daniu-de until this is fixed, could you please tell us which lines have to be removed to skip the backup?
> 
> For the web updater:
> 
> https://github.com/nextcloud/updater/blob/cbf2b53e5e7806a5135b4c1dbe8edbe97e9e78ac/index.php#L1345

Thank you very match, you save my time.
Is very useful solution/.

**Comment by Jolopu** [comment]
This solution only works for the next update. Then index.php gets replaced. It would be nice to have an entry in the config file to disable these backups one and for all.

**Comment by hregis** [comment]
Still no option to decide whether or not to have a backup during an upgrade? 
Why impose this??? 
Please consider this request

**Comment by Jolopu** [comment]
Yes, please. I always have to delete theses unnecessary backups after each update. It's just a waste of valuable server space.
