### ISSUE TITLE
updater constantly fails to remove folders

### ISSUE THREAD

**Issue by 2019-05-10** [nextcloud/updater#283]
[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[ ] Delete old files ...PHP Warning:  rmdir(/home/nextcloud/updater/../lib/l10n): Directory not empty in phar:///home/nextcloud/updater/updater.phar/lib/Updater.php on line 862
[✘] Delete old files failed
Could not rmdir: /home/nextcloud/updater/../lib/l10n
Update failed. To resume or retry just execute the updater again.
$ ~/updater]$ php updater.phar

The  web updater always fails to remove a bunch folders, making each update to a hours long experience of removing folders manually, restarting updater again, removing folders from updater folder (why aren't files just copied and the updater folder deleted in full at the end?), fixing missing files the updater always looses.

Today I tried the command line updater, since I understood the web updater may run into timeout issues.
But here I am again.

"Update failed. To resume or retry just execute the updater again."

executing the updater again, starts everything again, including backup which is not necessary after the first time (and in fact will probably result in a useless backup).

If indeed even the cli updater suffers from timeouts due to too long running operations, starting from scratch over an over again ist not going to help, instead it should remember the last step and proceed from there.

shared web server w/o any way to change settings
FreeBSD 11.3-RELEASE-p6

**Comment by kesselb** [comment]
> The updater needs to be able to work with shared hosts where limits are rather strict.

Nope. It's not the goal to support any shared web hosting out there. If rmdir returns false for whatever reason it seems more a workaround than a solution. Probably acceptable if a known quirks with rmdir. 

> FreeBSD 11.3-RELEASE-p6

Is not even officially supported.

**Comment by MorrisJobke** [comment]
> > FreeBSD 11.3-RELEASE-p6
> 
> Is not even officially supported.

Sorry to say that, but I will close the ticket. The updater itself remembers the step it is in and continues there, but if the commands return a failure, then there is not much we can do. Feel free to debug this more, but I don't see any obvious issues here.

if you have a special way to properly reproduce this then we can look into a solution, but just retry harder (which only sometimes work) and then patching out essential functionality (like the verification of the archive and the code) out is not really a solution.

**Comment by 2019-05-10** [comment]
Given the frustrated comments I've seen while searching for a solution, I can't say I am surprised you're just closing this.

> The updater itself remembers the step it is in and continues there, but if the commands return a failure, then there is not much we can do. 

What about really remembering the last step and  retrying from there? At least, that's what the updater itself suggests:
> Update failed. To resume or retry just execute the updater again.

Creating a new backup, downloading the same zip again, verifying, expanding, deleting bit by bit -- again and again? That's just unnecessary waste of resources and doesn't fix anything, but most likely serves only to make sure the installer runs in the timeout each time again as well.

Allowing to skip the backup, keeping the downloaded zip, keeping the extracted zip's folder, deleting only at the very end in one go -- these are all valid points and IMO very sensible to address.

At least the CLI updater is supposedly meant to be used by people knowing (more or less) what they do -- and I got there since it was suggested to be used when the web updater runs into timeouts.
That's not true either, as it seems.

The stuff I did was to make things work. I am not familiar with NC's code nor have I coded in PHP for a long time. I attached it to illustrate my points (and help others looking for a way to make things work). Using that as an excuse just confirms my first impression.

Hopefully this ticket, closed or not, helps others, stuck in  the same frustrating and poorly addressed situation.

**Comment by MorrisJobke** [comment]
> Creating a new backup, downloading the same zip again, verifying, expanding, deleting bit by bit -- again and again?

That should not happen. We actually really remember the state. There is a `.step` file in the updater directory that should avoid all of this.

> Allowing to skip the backup, keeping the downloaded zip, keeping the extracted zip's folder, deleting only at the very end in one go -- these are all valid points and IMO very sensible to address.

Skipping backup: #282

Keeping the downloaded zip works. It's the same step file I mentioned above. 

> At least the CLI updater is supposedly meant to be used by people knowing (more or less) what they do -- and I got there since it was suggested to be used when the web updater runs into timeouts.
> That's not true either, as it seems.

CLI updater uses the exact same code and is heavily tested. It seems to be a setup issue with your system. The only difference for the CLI updater are the CLI arguments (unattended upgrade, verbose mode) and that it can not run into the timeout of the webserver as it is not executed via the webserver.



> Hopefully this ticket, closed or not, helps others, stuck in the same frustrating and poorly addressed situation.

Sorry that you had such issues, but we try to make things work as good as possible. And saying that the updater itself works poorly is something I cannot confirm. It might be related that you run Nextcloud in a non-Linux environment which we don't support and don't want to spend time into as of now.

**Comment by 2019-05-10** [comment]
> That should not happen. We actually really remember the state. There is a `.step` file in the updater directory that should avoid all of this.

Well, it doesn't.
It's more than a year and at least one realese later and it still does not work.

```
[✘] Delete old files failed
Could not rmdir: /home/foo/nc/updater/../3rdparty/aws/aws-sdk-php/src

Update failed. To resume or retry just execute the updater again.
```
Manually deleting the folder and "just executing theupdater again" ... just starts from the top.
No ``.steps`` file left anywhere.

Any chance you could describe how that ``.steps`` file is supposed to look so one could create it manually?

**Comment by freaky33** [comment]
Still not working, please reopen the issue. I can't update normally since 4 versions.

**Comment by reloxx13** [comment]
same and it sucks, devs ignoring issues and just closing them.

**Comment by jb-ctrl** [comment]
> updater_two_modified_files.zip

i have the same issue now I downloaded your files but I don't know where I have to put the files. can you help me with that? I try to update 30.0.0 to 30.0.4 . thank you

**Comment by joshtrichards** [comment]
@jb-ctrl 

1. I suggest following the official manual update process rather than trying to use patched code from 5+ years ago. See https://docs.nextcloud.com/server/stable/admin_manual/maintenance/manual_upgrade.html

2. These rmdir issues are mostly occurring in environments with FreeBSD + NFS (or something similar) in-use. That matter is being tracked in #158. PR #594 targets that matter specifically. It's not merged yet. So another option for you would be to replace the `updater/` folder in your environment with the contents of that PR, but don't do that unless you're already super comfortable tinkering around with things.
