### ISSUE TITLE
Updater fails to parse datadirectory param in config.php

### ISSUE THREAD

**Issue by V1TA5** [nextcloud/updater#297]
**Problem:**
Updater gets stuck at Step3 (Backup) with error cant create file or folder.

**Cause:**
'datadirectory' parameter is set in config.php to use a custom data directory path.
Updater folder is created in the path set via datadirectory but backup uses default data path (and ignores 'datadirectory' in config.php )and thus cant find the updater folder.

**Solution:**
Check code (especialy step 3 backup process) for missing checks for datadirectory config.php value and add them.

**Workaround:**
Create soft link from datadirectory path to <Nextcloud-install-dir>/data

**Comment by MorrisJobke** [comment]
Should work as the backup code uses the data dir from the config:

https://github.com/nextcloud/updater/blob/1cd82f282225a7a52ca352cdb897aead18a8a274/lib/Updater.php#L355

And I have quite some instances where this works just fine and the /data/ directory is not present in the root of the nextcloud folder at all.

**Comment by SebastianBerlin** [comment]
Excuse me, I don't understand the workaround. I have similar the same problem: https://github.com/nextcloud/server/issues/27996#issuecomment-881889410

**Comment by joshtrichards** [comment]
Hi @V1TA5 - I'm attempting to clean up old Issues. Have you continued to experience this?
