### ISSUE TITLE
Release new server updates on GitHub instead of (extremely slow) download.nextcloud.com

### ISSUE THREAD

**Issue by EmberHeartshine** [nextcloud/updater#300]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Downloads from `download.nextcloud.com` are extremely slow, causing the updater to timeout/fail. I often have to `wget` the update zip into the downloads directory manually, then resume updating once that is complete. This often takes upward of 30-45 minutes on a gigabit connection, and is extremely bad UX.

**Describe the solution you'd like**
Use the GitHub releases function to distribute the NC software instead of self-hosting on slow servers. (in addition to the source code releases already offered.)

**Describe alternatives you've considered**
At present, finding a trustworthy mirror is the only alternative, but that still does not address the problem that the updater has since it only tries to download from `download.nextcloud.com`.

**Comment by MorrisJobke** [comment]
We are aware of this. Thus we are preparing to offload the desktop client distribution to GitHub, but this still takes some time. That is the root problem of our download server as the desktop client is requested by end users and not only by server admins and thus causing the whole problem. I hope that within the next days we will have sorted this out. Sorry for the trouble here.

**Comment by MorrisJobke** [comment]
You can also run your own updater server and specify a different url from there.

Specify your updater server via: https://github.com/nextcloud/server/blob/master/config/config.sample.php#L688
Updater server config: https://github.com/nextcloud/updater_server/blob/master/config/config.php#L115

**Comment by MorrisJobke** [comment]
Let's close this here as it is the bug tracker of the code not the infrastructure. We are working on this.

**Comment by EmberHeartshine** [comment]
It's been a year and a half and this is still an issue. "We are working on this" is clearly not true.
