### ISSUE TITLE
Add config.php option to specify location of updater folder

### ISSUE THREAD

**Issue by mmccarn** [nextcloud/updater#301]
My nextcloud data folder is located on a relatively slow NFS file share.  

When using the updater, these steps take longer than necessary:
* create backup
* verifying integrity
* extracting 
* move new files into place

I would like to override the default updater working folder setting to move it from <datadirectory>/updater-<instanceid> to another location.

**Comment by MorrisJobke** [comment]
The backup can be disabled with a CLI option nowadays. For the others I would like to keep the complexity of the updater low. If there are more people in the need of such a feature we can re-evaluate it but I would close this as of now as won't fix.
