### ISSUE TITLE
429 HTTP code on updating 

### ISSUE THREAD

**Issue by erikc96** [nextcloud/updater#303]
✘] Downloading failed
Download failed - HTTP status code: 429 - URL: https://download.nextcloud.com/server/releases/nextcloud-12.0.13.zip

Update failed. To resume or retry just execute the updater again.

**Comment by mritzmann** [comment]
I think a few days ago Nextcloud [had a few problems](https://help.nextcloud.com/t/nextcloud-com-slow-download-speed/71461/48?u=mritzmann). Now it should probably work again.
