### ISSUE TITLE
Web-Updater doesn't give error-information any more

### ISSUE THREAD

**Issue by mylaeus** [nextcloud/updater#310]
One of my nextcloud installations runs on a slow server. It normaly has errors while updating (can't find core/shipped.json, can't delete files or dicretories. I have a workaround to complete the update.
While updating from 19.0.4 to 20.0.1 the update stopped, but it gives no comment on the error. As I knew the wordaraund, I just tried an could end the update successfully. But it would be great to re-activate the error informations.

**Comment by MorrisJobke** [comment]
Actually we changed something: the error should be displayed inside an expandable details view:

https://github.com/nextcloud/updater/commit/d0ca75d0a17069a27e9a7f3b388a088b5215c266

That means there was a little text saying whatever the old text said plus in the details section the full response body.

Maybe there went something wrong. What was the specific step that failed?

**Comment by 2019-05-10** [comment]
> While updating from 19.0.4 to 20.0.1 the update stopped, but it gives no comment on the error. As I knew the wordaraund, I just tried an could end the update successfully. But it would be great to re-activate the error informations.

Could you please describe your workaround?
I am stuck with the missing error details on upgrade from 18.0.12 to 19.0.6 -- since there is apparently not even a log and there are several files the upgrader chokes upon it's difficult to figure out what file causes the final failure.

**Comment by mylaeus** [comment]
I normally get two kinds of errors. One is "[path-to-nextcloud]/core/shipped.json" is missing. This happens four times in one update-process. If the foulder "core" still exists, I upload the file from my backup. When the foulder doesn't exist, I create a new folder "core" and than uplod "shipped.json" to it. 
The second error is, that while "Deleting old files", several files can't be deleted in the first try. Then I just hit "Retry update" and the update-process continues. -
Good luck trying ...

**Comment by yafp** [comment]
I'm having the same issue while trying to update from 19.0.6 to 20.0.4

No error given/displays - which makes it really hard to start debugging.

![Screenshot_20210102_004241](https://user-images.githubusercontent.com/67605/103448010-9f36bc00-4c93-11eb-9194-025f6bbeb1e9.png)

**Comment by joshtrichards** [comment]
> I am stuck with the missing error details on upgrade from 18.0.12 to 19.0.6 -- since there is apparently not even a log and there are several files the upgrader chokes upon it's difficult to figure out what file causes the final failure.

The updater has it's own log file. It'll be in your `datadirectory` / adjacent to your `nextcloud.log`. It is called `updater.log`.
