### ISSUE TITLE
If an update Step fails, enhance the feedback

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/updater#325]
Some times ago I had a problem because the updates stuck in [Step 4](https://github.com/nextcloud/server/issues/23454)

Please enhance the Updater and enhance the information if an update fails. If possible harden the updater and enhance his doing and Information in case a problem appear. (Was able to solve it with simply removing the step file)
See also:
https://github.com/nextcloud/updater/issues/28

**Comment by joshtrichards** [comment]
Fixed in #472
