### ISSUE TITLE
Improve information about backups and pitfalls before doing an update

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/updater#33]
Let’s continue the discussion here @te-online @SamEliotFisher @tflidd @enoch85 cause the issue in the other repo was closed. ;)

@te-online maybe best check out the current state of the updater and see what’s there to improve. :)

**Comment by MorrisJobke** [comment]
We currently work on a much improved version of the updater: https://github.com/nextcloud/updater/pull/32

It already takes care of many problems we have seen in the past.

**Comment by te-online** [comment]
While you implement the magic of the underlying logic in the new updater, @MorrisJobke, we could take a look at how users/admins (we can't really draw a line here, can we?) would be able to use the updater (in real life) and what possibly could go wrong? – We can at least make sure that we avoid (UI-)errors, we solved in the old updater app already. 😊

**Comment by MorrisJobke** [comment]
I guess this is resolved by now. If there are things to clarify, feel free to open a more specific issue. Thanks
