### ISSUE TITLE
[Enhancement] Use federated update distribution

### ISSUE THREAD

**Issue by tacruc** [nextcloud/updater#334]
Sometime mostly, when new updated are released download.nextcloud.com is quite slow. On the other hand there are multiple thousands nextcloud servers out there in the internet and nextcloud has a great community.

Therefore, I was wounding if it might be worth it, to use nextcloud server to distribute the update, or apps. The apps and server it self has a checksum therefore federated distribution should not be a security issue.

The updater could register the download url at a central place. This place would hand e.g. 10 possible mirrors to the updater.
Additionally, the Tarball could be spitted in reasonable chunks  to enable downloads from different servers, to overcome the problem that private servers are not symmetrically connected.

Providing updates for nextcloud could be an OptIn option, maybe a kind of traffic limit, e.g. total download or speed.

**Comment by MorrisJobke** [comment]
We plan to move our releases off to different servers via the updater server (most likely to our download server and to github releases). That will be possible via #326. Therefore I would close this here as it would involve a lot of logic inside the updater and I would like to keep it as simple as possible to also avoid bugs. I hope that this is okay for you.
