### ISSUE TITLE
Please clear the app_install_overwrite array before updating to a major version

### ISSUE THREAD

**Issue by szaimen** [nextcloud/updater#337]
Hi,

I've already seen many installations broken after major upgrades because the updater automatically enabled apps that are technically incompatible with the new version but this check is overwritten by the app_install_overwrite array. 
Clearing this array automatically (maybe as a first step in the updater) before running the actual upgrade to a major version would solve those problems.

This is how we've solved this problem in the NcVM: https://github.com/nextcloud/vm/pull/1835

Cheers!

**Comment by szaimen** [comment]
Though, I am not sure if this should get reported in the server repository?

**Comment by joshtrichards** [comment]
Let's track this in nextcloud/server#43026 since the Updater doesn't touch this sort of stuff on its own and all the app upgrades are handled in `occ upgrade`.

**Comment by joshtrichards** [comment]
Duplicate of nextcloud/server#43026
