### ISSUE TITLE
Different "datadirectory" in CLI mode possible?

### ISSUE THREAD

**Issue by sokai** [nextcloud/updater#365]
Hi,

on a shared hosting I have differen paths for web/HTTP and CLI.

My current solution comes from https://github.com/nextcloud/server/issues/19181#issuecomment-579366622 and it works very well wil the `occ` CLI command.

I created the file `config/local.config.php` with this content:

```php
<?php

$local = [
    'datadirectory' => '/domains/[…]/[…]/nextcloud_data',
    'tempdirectory' => '/domains/[…]/[…]/nextcloud_data/tmp'
];

if ( \OC::$CLI )
{
    // CLI config parameters
    $CONFIG['datadirectory'] = $local['datadirectory'];
    $CONFIG['tempdirectory'] = $local['tempdirectory'];
} else {
    $web_path = '/var/www/vhosts/[…]';
    // WEB config parameters
    $CONFIG['datadirectory'] = $web_path . $local['datadirectory'];
    $CONFIG['tempdirectory'] = $web_path . $local['tempdirectory'];
}

```

Currently I try to run `updater.phar`, but I get this error message:
> Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4
>
> PHP Warning:  fopen(/var/www/vhosts/[…]/domains/[…]/[…]/nextcloud_data/updater.log): failed to open stream: No such file or directory in phar:///domains/[…]/[…]/nextcloud/updater/updater.phar/lib/Updater.php on line 1110
> Could not open updater.log

So: Can you plz tell me (or maybe implement it?), how I can use different paths for `datadirectory` while using the `updater.phar`?

I need such an option because running the web version of the updater gets regularly stuck during the backup step and I wanna have a proper upgrade solution. (And I'm not the only one, like you can see in a second comment: https://github.com/nextcloud/server/issues/19181#issuecomment-744052487.)

Thanks and BK!

**Comment by MorrisJobke** [comment]
Hi @sokai, as of now there is no plan to implement such a feature, because it is really special to your shared hoster setup. Unfortunately we can't support all of them out there. We recommend to use a VPS instead to run Nextcloud.

**Comment by sokai** [comment]
@MorrisJobke Thank you for the feedback!

Let me say that I agree with the basic message, that *you* will not implement it and I see the VPS point (but currently I have no other option).

**But:** Is there a possibility to have this featere as a user contribution (that you can merge by a PR)? E.g. I would/could try to find a way to add a new command option (like `no-backup`).

Thanks in advance + KR!

**Comment by MorrisJobke** [comment]
The user contribution still adds the burden of maintaining it on our side. It adds complexity that we need to deal with. There are then corner cases that always need to be tested, etc.

so most likely we will not accept the PR. Sorry

**Comment by Megachip** [comment]
hmm... it worked in 27.1.3, after updating to 27.1.11 Ive running into the same issue.
