### ISSUE TITLE
After failing webupdater and CLI my NC is not starting

### ISSUE THREAD

**Issue by zkzkzk2015** [nextcloud/updater#367]
root@nextcloud:/var/www/html/updater# sudo -u www-data php updater.phar
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 21.0.0.

Update to Nextcloud 21.0.1 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[✔] Extracting
[✔] Enable maintenance mode
[✔] Replace entry points
[ ] Delete old files ...PHP Warning:  unlink(/var/www/html/updater/../.htaccess): Permission denied in phar:///var/www/html/updater/updater.phar/lib/Updater.php on line 866
[✘] Delete old files failed
Could not unlink: /var/www/html/updater/../.htaccess

Update failed. To resume or retry just execute the updater again.

I am running NC 21 on a Ubuntu Server 20.04.2 LTS on a digitalocean droplet.

**Comment by kesselb** [comment]
> [ ] Delete old files ...PHP Warning: unlink(/var/www/html/updater/../.htaccess): Permission denied in phar:///var/www/html/updater/updater.phar/lib/Updater.php on line 866

Fix the permission
