### ISSUE TITLE
Updating to Nextcloud 21 not possible with PHP memory limit of 128MB and below

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/updater#368]
- I want to update my personal instance to 21
- I’m on Gandi Simple Hosting, where the PHP memory limit is hard set to 128MB (except the XXL plan which is 5 times as expensive ;)
- On the "Verifying integrity" step of the updater I get this error:

```
PHP Fatal error:
Allowed memory size of 134217728 bytes exhausted
(tried to allocate 155248904 bytes)
in updater/updater.phar/lib/Updater.php on line 637
```

The size lines up with the size of the zip file:
`155240687 Apr 12 10:26 nextcloud-21.0.1.zip`

So in the "Verifying" step it loads that whole file in memory to check the integrity?

@st3iny said:
> I did some research and I don't know a way to improve this without changing the signing process. The openssl_verify method can only take a buffer of data and thus the whole file has to be read before passing it on.
> It would be way more efficient to pass a stream or file path instead.

**Comment by SteffoSpieler** [comment]
I have the same issue. Though I want to update to 20.0.9.

**Comment by MorrisJobke** [comment]
> * 
> 
> * I’m on Gandi Simple Hosting, where the PHP memory limit is hard set to 128MB (except the XXL plan which is 5 times as expensive ;)

We recommend to use 512 MB - most likely we need to increase the required minimum to 256 or 512 MB as well: https://docs.nextcloud.com/server/21/admin_manual/installation/system_requirements.html. And there isn't much we can do here.

Let me close it as it is a won't fix from the updater side, as we use PHP methods directly.

**Comment by MorrisJobke** [comment]
> * 
> 
> * I’m on Gandi Simple Hosting, where the PHP memory limit is hard set to 128MB (except the XXL plan which is 5 times as expensive ;)

And try to migrate to a VPS then instead. We recommend to use VPS over shared hosting anyways, as it is not that expensive - hetzner starts at ~3 € per month for example and allows for proper configuration of your PHP environment: https://www.hetzner.com/cloud
