### ISSUE TITLE
Updating from 20.0.8 to 20.0.9 installs 21.0.1 instead

### ISSUE THREAD

**Issue by vanMacG** [nextcloud/updater#370]
I already had the same issue on version 19 (see [server-issue#24349](https://github.com/nextcloud/server/issues/24349) & #314)
Now again: I'm on 20.0.8, admin overview offers 20.0.9, updater pulls 21.0.1.
![1](https://user-images.githubusercontent.com/8269814/114825641-c8083a80-9dc6-11eb-9b14-7c57c0d8dd11.PNG)
![2](https://user-images.githubusercontent.com/8269814/114825646-c9d1fe00-9dc6-11eb-9770-f48c34f7b0fe.PNG)

**Comment by shorshe** [comment]
Same Issue here.

**Comment by DZrenner** [comment]
Same here.

**Comment by Micha-Btz** [comment]
For me it is solved. The updater offers me 20.0.9 now.

**Comment by stephang** [comment]
Had the same issue last week, works now.

**Comment by vanMacG** [comment]
Fixed with [update_server#558](https://github.com/nextcloud/updater_server/pull/558)
