### ISSUE TITLE
Avoid Upgrading Apps to an Incompatible Version

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [nextcloud/updater#380]
My instance is upgraded to 21.0.3. And the News app was also upgraded to 16.0.0.
However it requires 64-bit system, while my system is armv7.
https://github.com/nextcloud/news/blob/02cbdc9635a63c1789c7a747e67a3db8676abf2d/appinfo/info.xml#L42
So I get this:
```
App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.
```

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/27797
