### ISSUE TITLE
Ignore the custom apps folder

### ISSUE THREAD

**Issue by oparoz** [nextcloud/updater#40]
I had to move it out of the root for the update and back in after it was done.
I think it can be safely ignored and the path is in `config.php`

**Comment by Bullnados** [comment]
Is here something going on?
My webhoster is all-inkl. If there is no tmp folder and a path to it in in config.PHP I get opendir(/tmp): failed to open dir: errors 
ATM I habe to move the tmp folder outside nextcloud root folder every update.

**Comment by MorrisJobke** [comment]
Fixed with #107

**Comment by Degenerate76** [comment]
This appears to have reoccurred.

<img width="468" alt="NexcloudUpdateFail" src="https://user-images.githubusercontent.com/32216898/59431393-bd507900-8ddc-11e9-9e42-f26debea6084.png">
