### ISSUE TITLE
Feature Request: Change Updater Base Path

### ISSUE THREAD

**Issue by fservida** [nextcloud/updater#406]
Updater Base Path should be configurable (eg. in config.php) to another folder than the base "data" folder.
Especially on NFS mounts, the backup process is extremely long due to the small files.

Additionally the updater data is included with the "data" backups, which is also not useful.

**Comment by solracsf** [comment]
Check https://github.com/nextcloud/updater/pull/420

**Comment by fservida** [comment]
awesome, thank you, will close as soon as your PR is merged into NC25

**Comment by solracsf** [comment]
Closed by https://github.com/nextcloud/updater/pull/420
