### ISSUE TITLE
Updater fails at Step 5 (Integrity Check) and cannot be restarted

### ISSUE THREAD

**Issue by benedetto** [nextcloud/updater#415]
Currently on Nextcloud 22.2.5 I got an update notification for 22.2.6. When starting the updater via the web interface, it failed at Step 5 (Cheching the integrity of the downloaded archive). When I go back to the admin page and click "open updater" again, I get only a blank page with the message "Step 5 is currently in process. Please reload this page later." - even after waiting one day.

If I try to start an update from the commend line via `occ upgrade` it says `Nextcloud is already latest version`.

I currently don't see any possibility to reset the whole thing into a state where I can start the update from zero. Is there any way to do so?

**Comment by joshtrichards** [comment]
Hi @benedetto Thanks for your report. 

Until the updater steps finish, an upgrade (via `occ upgrade`) won't be possible. The details will be your `updater.log` about why things are hanging.

Yes, you can reset by removing: `data/updater-$INSTANCE_ID/.step`

**Comment by joshtrichards** [comment]
To run the Updater from the command line, use the Updater command line instructions (`occ upgrade` is not the Updater):

- https://github.com/nextcloud/updater?tab=readme-ov-file#updater--occ-upgrade
- https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html#using-the-command-line-based-updater

To reset things: 

- You can remove them manually (as noted above in some of the comments), but the safest is to run occ maintenance:repair which should accomplish the same thing (along with some other things that shouldn't hurt).

Are you by any chance in a low RAM environment (i.e. #505)? The integrity check step requires approximately the same mount of memory as the current size of the downloaded archive (~220MiB-250MiB today). You may need to do a fully manual update in that case: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html
