### ISSUE TITLE
Updater should provide a option to let user decide whether backup user data or not

### ISSUE THREAD

**Issue by Halry** [nextcloud/updater#417]
Each update it try to create backup in whether differential or full is useless if user already created snapshot before update. And backing up user's data is costing too much space. Only backing up nextcloud files is enough maybe?

It cost 104GB for users' data.
<img width="317" alt="image" src="https://user-images.githubusercontent.com/5312805/166628952-372bbd5a-10d8-497e-ad6c-a731e9c83077.png">

<img width="94" alt="image" src="https://user-images.githubusercontent.com/5312805/166628981-0dd0c32b-0752-4504-82ba-35a5c0e7ab81.png">

**Comment by kesselb** [comment]
Hi,

The updater **does not** backup user data.
`--no-backup` to skip the backup for the cli updater.
