### ISSUE TITLE
»Updater« section in settings should be all the way down

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/updater#42]
Ideally in the future fully integrated with the »Version« section. But for now it’s fine if it’s just all the way down. Right now it’s a bit weird just being inside somewhere with the rest.

@MorrisJobke

**Comment by MorrisJobke** [comment]
For me it is the last entry:

![bildschirmfoto von 2016-10-04 17-16-50](https://cloud.githubusercontent.com/assets/245432/19080133/5dfb1f96-8a56-11e6-8449-a0e7ddc8825e.png)

**Comment by jancborchardt** [comment]
Ah ok – it was different in older versions of Nextcloud where we didn’t have the separate settings view yet. I judged from a gif you posted in another issue/PR.

Looks fine on the current version so closing, not really worth to fix it in the older one.
