### ISSUE TITLE
php 8.1 error 

### ISSUE THREAD

**Issue by phonon112358** [nextcloud/updater#428]
Hi, 

I am using NC 24.0.1 and php 8.1.
I would like to update to 24.0.4. However, the web-based updater gives me an php error message: `<br />
<b>Deprecated</b>:  Return type of RecursiveDirectoryIteratorWithoutData::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/nextcloud/updater/index.php</b> on line <b>40</b><br />
{"proceed":true}`
![2022-08-12 at 22-00-52](https://user-images.githubusercontent.com/22647281/184435009-f8e20306-c3b8-4d28-bfab-889387d4730c.png)

A very similar issue is https://github.com/nextcloud/server/issues/33295

Is this issue solved already in future versions of the updater? Do I need to edit the updater/index.php file just once?

**Comment by VVD** [comment]
In 24.0.4 it isn't fixed.

**Comment by phonon112358** [comment]
@VVD How have you updated to NC 24.0.4 ? I haven't achieve this yet...

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/updater/pull/429

**Comment by phonon112358** [comment]
I can confirm that https://github.com/nextcloud/updater/pull/429 solves this issue

**Comment by VVD** [comment]
> @VVD How have you updated to NC 24.0.4 ? I haven't achieve this yet...

I fixed `nextcloud/updater/index.php` manually and run updater again.

**Comment by phonon112358** [comment]
> > @VVD How have you updated to NC 24.0.4 ? I haven't achieve this yet...
> 
> I fixed `nextcloud/updater/index.php` manually and run updater again.

yes, in the meantime, I have done that too... ;)
