### ISSUE TITLE
Updater app doesn’t need a navigation on the left

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/updater#43]
There is only one entry on the left … the navigation is useless. ;)

We can just remove it, right? @MorrisJobke

**Comment by MorrisJobke** [comment]
> We can just remove it, right?

Yes. I will do so

**Comment by jancborchardt** [comment]
@MorrisJobke thanks!

**Comment by crumbking** [comment]
+1   #2609

**Comment by crumbking** [comment]
same here: Updater UI on phone only half visible. Lot of whitespace

**Comment by jancborchardt** [comment]
@crumbking that’s a different issue, please open it separately :)

**Comment by MorrisJobke** [comment]
Duplicate of #136
