### ISSUE TITLE
Show if an Update Is Available and Exit

### ISSUE THREAD

**Issue by mritzmann** [nextcloud/updater#430]
## Is your feature request related to a problem?

I would like to use a system monitoring tool to check whether a Nextcloud update is available or not. The monitoring tool can execute commands per SSH, but there is no suitable endpoint/script/command which can be used to check for updates.

See also: https://help.nextcloud.com/t/monitor-whether-updates-are-available/143537

## Describe the solution you'd like

A new option for `updater.phar`:

* `--only-check`: Show if an update is available and exit

Exit codes:

* Exit 0: OK  - There is no update
* Exit 1: Warning - There is an update available

Exit codes optional:

* Exit 2: Critical - The update is urgent
* Exit 3: Unknown - Something failed

(More information about these exit codes and their meaning can be found at [the Icinga documentation](https://icinga.com/docs/icinga-2/latest/doc/03-monitoring-basics/#check-result-state-mapping). The common [nagios plugins](http://nagios-plugins.org/doc/man/index.html) use the same exit codes to distinguish between ok, warning, critical and unknown.)

**Comment by joshtrichards** [comment]
Update availability monitoring functionality was recently added to the `serverinfo` monitoring endpoint in nextcloud/serverinfo#434

**Comment by joshtrichards** [comment]
Closing as being implemented via the monitoring endpoint in nextcloud/serverinfo#434.

https://github.com/nextcloud/serverinfo/

Feel free to re-open, with an explanation, if using the monitoring endpoint for this functionality doesn't meet your needs.
