### ISSUE TITLE
Updating from 25.0.0 beta5 to beta6 shows no update

### ISSUE THREAD

**Issue by PVince81** [nextcloud/updater#436]
### Steps

1. Install 25.0.0 beta5 locally (in my case I also installed the recommended apps)
2. Go to the settings page in admin/overview
3. See that 25.0.0 beta6 is available
4. Click on "Open updater"
5. Expect an update but nothing happens

### Expected
Update available both on settings page and inside the updater

### Actual
<img width="386" alt="image" src="https://user-images.githubusercontent.com/277525/190987751-56c6048c-e704-4f44-b4e4-aeddd0e5e45f.png">

<img width="463" alt="image" src="https://user-images.githubusercontent.com/277525/190987803-2b36d2f2-66d4-4b5c-8782-a5fcaae36430.png">

@blizzz

**Comment by blizzz** [comment]
@PVince81 can you reproduce with `php updater/updater.phar`?

**Comment by PVince81** [comment]
```
# sudo -uwwwrun php updater/updater.phar 
Nextcloud Updater - version: v25.0.0beta3-17-gef6cf2d

Current version is 25.0.0 beta 5.

No update available.

Nothing to do.
```

**Comment by PVince81** [comment]
oh, updater version beta3 ??

from the beta5 tarball:
```
~/temp/nextcloud-25.0.0beta5/updater
  % php updater.phar --version
update v25.0.0beta3-17-gef6cf2d
```

beta6 tarball:
```
% php updater/updater.phar --version
update v25.0.0beta3-17-gef6cf2d
```

**Comment by blizzz** [comment]
It works for me when i switch to stable channel and switch back to beta channel.

**Comment by blizzz** [comment]
> oh, updater version beta3 ??
> 
> from the beta5 tarball:
> 
> ```
> ~/temp/nextcloud-25.0.0beta5/updater
>   % php updater.phar --version
> update v25.0.0beta3-17-gef6cf2d
> ```
> 
> beta6 tarball:
> 
> ```
> % php updater/updater.phar --version
> update v25.0.0beta3-17-gef6cf2d
> ```

that refers only to the last time the updater was build.

**Comment by blizzz** [comment]
I think originally the updater was not intended to be tagged like the server repo and bundled apps, for it is not build each time.

**Comment by blizzz** [comment]
I could reproduce it only in one of four attempts. I want to blame browser cache… It should not bug you for more then 30minutes though, for that is how long the result from the updater server is cached. During installation, the timestamp is saved, with an empty result, i.e. in that case nothing should be offered you in the 30minutes after installation.

To reset the timestamp, run `php occ config:app:set --value="0" core lastupdatedat` and visit admin settings again.

**Comment by blizzz** [comment]
Ah, one another thing is: if the release channel is not set in config.php, the updater defaults to stable, therefore the empty result. Nextcloud server itself defaults to whatever is set in version.php, and that's beta. This is why toggling stable and beta works is the workable workaround.

**Comment by PVince81** [comment]
in my local dev setup switching the channel to stable then back to beta, and then running
`php occ config:app:set --value="0" core lastupdatedat`

this made the updater go through!
