### ISSUE TITLE
Rebuild console updater.phar to use updatedirectory instead of datadirectory for backups and logs

### ISSUE THREAD

**Issue by Delagen** [nextcloud/updater#447]
Current updater.phar differ from updater/index.php in case of storage place of update files.

**Comment by szaimen** [comment]
@blizzz @come-nc @kesselb @PVince81 can we create a workflow for this to be able to rebuild and create a pr automatically with the updated updater.phar?

**Comment by come-nc** [comment]
> @blizzz @come-nc @kesselb @PVince81 can we create a workflow for this to be able to rebuild and create a pr automatically with the updated updater.phar?

Yes you can :-)

**Comment by come-nc** [comment]
More seriously I think we have CI for this, and the only reason it was broken is that a PR that was created before the CI was in place got merged. Once we fix it the CI should make sure it does not get broken again.
