### ISSUE TITLE
Repair warning

### ISSUE THREAD

**Issue by fynnsh** [nextcloud/updater#454]
`Migrate old user accessibility config
 Done
   50/50 [============================] 100%
Cleanup old theming cache
 Starting ...
 0/2 [>---------------------------]   0%
Repair warning: Failed to delete folder: "34", error: 
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_photos_albums' doesn't exist
Repair warning: Failed to delete folder: "images", error: An exception occurred while executing a query: SQLSTATE[42S02] Done
 2/2 [============================] 100%`

Anyone has the same warning while upgrading from 24.0.7 to 25.0.1

**Comment by joshtrichards** [comment]
Resolved by nextcloud/photos#1491
