### ISSUE TITLE
Updater tries to update Nextcloud 10.0 to Owncloud 9.1

### ISSUE THREAD

**Issue by caco3** [nextcloud/updater#46]
![screenshot_20161027_220956](https://cloud.githubusercontent.com/assets/1783586/19783399/1b8e6444-9c92-11e6-9f47-dfa7246f2f15.png)

See also https://github.com/nextcloud/notifications/issues/32

**Comment by LukasReschke** [comment]
https://help.nextcloud.com/t/notification-about-an-upgrade-to-owncloud-9-1-1-in-nextcloud-10-stable/4573
