### ISSUE TITLE
[Bug]: No Update possible with extra directory

### ISSUE THREAD

**Issue by KIrlenb** [nextcloud/updater#470]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I want update Nextcloud, but got this: Check for expected files
The following extra files have been found:

### Steps to reproduce

1. try update
2. try update
3. try update

### Expected behavior

Normal update

### Installation method

Official All-in-One appliance

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Other

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
nothing
```

### List of activated Apps

```shell
nothing
```

### Nextcloud Signing status

```shell
nothing
```

### Nextcloud Logs

```shell
nothing
```

### Additional info

nothing

**Comment by joshtrichards** [comment]
Hi @KIrlenb: This is a configuration/installation issue (unless you're saying the list of extra files shown is literally blank). 

The listed extra files - that aren't provided by Nextcloud - were found in the Nextcloud installation directory. You'll want to inspect what the reported files are and what they're doing there. 

If you run into difficulty, please post over at the [Nextcloud Help Forum](https://help.nextcloud.com) to get assistance and feedback on your installation.
