### ISSUE TITLE
Re-enable disabled apps after update.

### ISSUE THREAD

**Issue by STaRDoGG** [nextcloud/updater#479]
I'm always frustrated when: My features disappear each time I do an update, and then remember that after every single update I have to go back and manually re-enable pretty much all of my previously enabled apps.

### Describe the solution you'd like

For the updater to automatically re-enable them when done updating. Or if concerned about 1 or more apps potentially breaking the instance after re-enabling, allow adding a flag to the update command(s)/Update UI to optionally re-enable after, with a warning mentioning potential breakage. Perhaps even add this option as a setting where users can toggle it on/off.

The logs should show which app(s) break the instance if it were to happen.

### Describe alternatives you've considered

There are no alternatives.

**Comment by joshtrichards** [comment]
> For the updater to automatically re-enable them when done updating.

This is current behavior. Any app that has a compatible upgrade candidate (either shipped or in the app store) gets upgraded.

> I have to go back and manually re-enable pretty much all of my previously enabled apps.

What are some of the apps not being upgraded to compatible versions? 

Also, what is your Nextcloud installation method (snap, Docker, bare metal, etc.)?

**Comment by STaRDoGG** [comment]
@joshtrichards It was 10 months between my OP and your reply, so maybe some changes were added regarding this since then. I haven't really noticed the issue since switching to the LSIO image which I don't have to manually update myself anymore.

I'll just close this issue for now, and reopen if I come across it again.
