### ISSUE TITLE
10.0.1 is recent even on beta channel

### ISSUE THREAD

**Issue by My1** [nextcloud/updater#49]
I have a nc install which is on 10.0.1 I threw multiple update checks because I want to update to the 11 beta but for some reason it doesnt see the update to 11 beta. it does find something in daily though, but I'd rather have the beta.

**Comment by MorrisJobke** [comment]
We haven't enabled the beta via updater yet.

https://github.com/nextcloud/updater_server/pull/16 <- this is the change for the updater server that is then shipping the beta.

We first want some basic feedback from the core developers first and then will much likely enable the updater during next week. 😉

**Comment by juliushaertl** [comment]
Beta 2 is now on beta channel, so we can close this, i guess.

**Comment by My1** [comment]
yep, thanks,

**Comment by MorrisJobke** [comment]
Ah yes - forgot to close that one. The beta channel is live since 11 hours.
