### ISSUE TITLE
Add PHP version to updater HTTP request

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/updater#53]
Considering that 11 requires 5.6 and some people may click upgrade without reading we should add the PHP version to the HTTP string and have some server-side logic for now to filter those.

Thoughts, @morrisjobke?

**Comment by MorrisJobke** [comment]
Makes sense 👍 We should provide the version for all maintenance releases.

**Comment by MorrisJobke** [comment]
Fix for updater server is in nextcloud/updater_server#19
