### ISSUE TITLE
Solution to Stuck on update process. Step 5 is currently in process. Please reload this page later > (Plesk Nextcloud) Verify integrity ..., stderr: PHP Fatal error:.............

### ISSUE THREAD

**Issue by jcvikl** [nextcloud/updater#577]
I got also same problem with 25...Message - Execution filemng has failed with exit code 255, stdout: Nextcloud Updater - version: v25.0.0beta3-17-gef6cf2d Current version is 25.0.1. I have a huge problem with Step 5 is currently in process. Please reload this page later. Its the same error on other instance with version 29.
_Originally posted by @jcvikl in https://github.com/nextcloud/updater/issues/502#issuecomment-2296334721_
 I solve problem, this way -After reviewing the forums and debates... I don't know if all the steps are necessary, but... from  25.0.1 to 29. Nextcloud goes with (is installed with Plesk)
1.  For all the beginners - upgrade working files are hidden into .nextcloud directory. But first i change vi /usr/local/psa/admin/conf/php.ini - memory_limit = 512M. This could be problem in future, because "DO NOT MODIFY THIS FILE BECAUSE IT WAS GENERATED AUTOMATICALLY, ; SO ALL YOUR CHANGES WILL BE LOST AFTER YOU UPGRADE PLESK.
- it could went back to 256M if newer Plesk change this again to 256M.
2. I went to hidden dir var/www/vhosts/webdir/.nextcloud/data/IDfromconfig/updater-IDfromconfig/ and rm .step (delete temporary file where you stuck)
3. went to installed nexcloud folder  and open  var/www/vhosts/webdir/nextcloud/updater/index.php and comment lines:
 //	if ($stepState === 'start') {
//		die(
//			sprintf(
//				'Step %s is currently in process. Please reload this page later.',
//				$stepNumber
//			)
//		);
//	}
and comment step bellow 
		//	case 5:
		//		$updater->verifyIntegrity();
		//		break;

and return to instance on web domain/index.php/settings/admin/overview and run updater one by one. At 28 or 27 I change php from 8.0 to 8.1. 

I played also with 
sudo -u www-data php /var/www/nextcloud/occ maintenance:repair
sudo -u www-data php /var/www/nextcloud/updater/updater.phar --no-interaction 
but on Alma were ownership etc problems, so I solve then with 1-3.

**Comment by joshtrichards** [comment]
Hi @jcvikl - Glad you got it working :+1:  This channel is only for development related bug discussions. I'm going to close this issue since there isn't anything actionable here for us. You may want to consider posting your resolution steps on the Community Help Forum for others to benefit from - https://help.nextcloud.com
