### ISSUE TITLE
Problems with open_basedir

### ISSUE THREAD

**Issue by flesser** [nextcloud/updater#62]
Using the updater app to update from 10.0.1 to 10.0.2 I can't get past the **Check for write permissions** step since I'm using PHP open_basedir on my server:
```SplFileInfo::isDir(): open_basedir restriction in effect. File(/var/www/nextcloud/updater/../..) is not within the allowed path(s): ([...]:/var/www/nextcloud/)```

I wonder why the updater needs to access `/var/www/nextcloud/updater/../..` i.e. `/var/www/`, which is (intentionally) not on my open_basedir allowed paths?

**Comment by lauhayden** [comment]
I guess this is a fundamental issue with a web-based updater, but security features like open_basedir and file permissions are always going to block nextcloud from updating. I'm going to keep updating manually unless there's a workaround - it's about the same fuss to manually update as to disable all the security restrictions, then re-enable them afterwards.

**Comment by fireba11** [comment]
Shared webs usually don't allow access outside the main web folder, and if you don't put nextcloud in a subfolder you will run into that issue. Not sure of that check is not just plain wrong and goes one folder up too far.

**Comment by webenhanced** [comment]
Perhaps the installation instructions could mention that the updater needs write access to the directory above the installation.

In my case, I installed in a subdomain which, by default, does not have a httpdocs or public_html directory underneath it. So I had to give the subdomain write access to the main domain's home directory. Not ideal at all.

When making the subdomain (under Plesk in my case), I could have placed a httpdocs directory under the subdomain directory and then all would have been good.

**Comment by ThomasCr** [comment]
I also have the same problem which the common ispconfig hosted domain.

```
root@srv1:/var/www/clients/client1/web2# ls -lah
insgesamt 448K
drwxr-xr-x 22 root root    4,0K Jun 20  2016 .
drwxr-xr-x  6 root root    4,0K Jun 20  2016 ..
drwxr-xr-x  2 web2 client1 4,0K Jul  9  2013 cgi-bin
drwx--x--- 15 web2 client1 4,0K Apr 27 18:19 cloud
drwxr-xr-x  5 root root    4,0K Apr 27 00:30 log
drwx--x---  9 web2 client1 4,0K Apr 27 18:19 private
drwxr-xr-x  2 root root    4,0K Apr 23 21:44 ssl
drwxrwx---  3 web2 client1 360K Apr 27 17:56 tmp
drwx--x--x 10 web2 client1 4,0K Apr 23 20:58 web
drwx--x---  2 web2 client1 4,0K Jul  9  2013 webdav

```
ispconfig protect the installation with the follow open_basedir: 
(/var/www/clients/client1/web2/cloud:/var/www/clients/client1/web2/private:/var/www/clients/client1/web2/tmp:/..some other dirs..)
So by default it is not possible to access the provided root folder. Before with owncloud I had no problems with the online updater... dont understand why he want to access this folder.

**Comment by PhrozenByte** [comment]
@LukasReschke: This issue is falsely labeled as `enhancement`. This issue is rather a bug. See #105
