### ISSUE TITLE
Stuck on step 6 (10.0.1 -> 10.0.0.2)

### ISSUE THREAD

**Issue by ronnicek** [nextcloud/updater#65]
Update stucks after extract, message was something around "Extract is still running, please reload page later.". So I reload the page and I just got maintenance window (and no PHP process is running with 100% CPU as normally running during update).

I checked the log and there are interesting things.. like totally wrong version?! (I am using 10.0.0.1, not 9.1.2.2).

> 2016-12-11T03:12:47+0000 BdnOAQlxGZ [info] end of setMaintenanceMode()
> 2016-12-11T03:12:47+0000 BdnOAQlxGZ [info] endStep("3")
> 2016-12-11T03:12:47+0000 BKTreGWqnl [info] request to updater
> 2016-12-11T03:12:47+0000 BKTreGWqnl [info] currentStep()
> 2016-12-11T03:12:47+0000 BKTreGWqnl [info] Step 3 is in state "end".
> 2016-12-11T03:12:47+0000 BKTreGWqnl [info] POST request for step "4"
> 2016-12-11T03:12:47+0000 BKTreGWqnl [info] startStep("4")
> 2016-12-11T03:12:47+0000 BKTreGWqnl [info] createBackup()
> 2016-12-11T03:13:12+0000 BKTreGWqnl [info] end of createBackup()
> 2016-12-11T03:13:12+0000 BKTreGWqnl [info] endStep("4")
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] request to updater
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] currentStep()
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] Step 4 is in state "end".
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] POST request for step "5"
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] startStep("5")
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] downloadUpdate()
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] getUpdateServerResponse()
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] updaterServer: https://updates.nextcloud.org/updater_server/
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] releaseChannel: stable
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] internal version: 9.1.1.5
> 2016-12-11T03:13:13+0000 K3sFqCI8Lu [info] getUpdateServerResponse response: Array
> (
>     [version] => 9.1.2.2
>     [versionstring] => Nextcloud 10.0.2
>     [url] => https://download.nextcloud.com/server/releases/nextcloud-10.0.2.zip
>     [web] => https://docs.nextcloud.org/server/10/admin_manual/maintenance/manual_upgrade.html
>     [autoupdater] => 1
> )
> 
> 2016-12-11T03:13:24+0000 K3sFqCI8Lu [info] end of downloadUpdate()
> 2016-12-11T03:13:24+0000 K3sFqCI8Lu [info] endStep("5")
> 2016-12-11T03:13:24+0000 89eZ7ioUZv [info] request to updater
> 2016-12-11T03:13:24+0000 89eZ7ioUZv [info] currentStep()
> 2016-12-11T03:13:24+0000 89eZ7ioUZv [info] Step 5 is in state "end".
> 2016-12-11T03:13:24+0000 89eZ7ioUZv [info] POST request for step "6"
> 2016-12-11T03:13:24+0000 89eZ7ioUZv [info] startStep("6")
> 2016-12-11T03:13:27+0000 89eZ7ioUZv [info] extractDownload()
> 2016-12-11T03:13:27+0000 89eZ7ioUZv [info] storage location: /var/www/owncloud/data/updater-ocn0mgjslvwm/downloads/
> 2016-12-11T03:14:46+0000 UCoq2ncdFU [info] request to updater
> 2016-12-11T03:14:46+0000 UCoq2ncdFU [info] currentStep()
> 2016-12-11T03:14:46+0000 UCoq2ncdFU [info] Step 6 is in state "start".
> 2016-12-11T03:14:56+0000 89eZ7ioUZv [info] end of extractDownload()
> 2016-12-11T03:14:56+0000 89eZ7ioUZv [info] endStep("6")

Any ideas?

**Comment by LukasReschke** [comment]
What happens if you disable maintenance mode in your config file?

**Comment by ronnicek** [comment]
Then login screen.. Nextcloud is on version 10.0.1 and there is notification about 10.0.2 again.

**Comment by MorrisJobke** [comment]
@ronnicek Thanks for this feedback - sorry for the late response.

> I checked the log and there are interesting things.. like totally wrong version?! (I am using 10.0.0.1, not 9.1.2.2).

The version that is shown in the log is the version it tries to update to.

Can you check the content of `data/updater-INSTANCEID` and it's subfolders? What is in there?

**Comment by ronnicek** [comment]
So I have version 10.0.0.1 and it tries to update to 9.1.2.2? Heh..

There is folder backup and downloads and file .step. What exactly I should look for?

In step file is:
> {"state":"end","step":6}

In backups is folder: nextcloud-9.1.1.5
In backups/nextcloud-9.1.1.5/version.php is:
> $OC_Version = array(9,1,1,5);
> $OC_VersionString = '10.0.1';

In downloads is folder: nextcloud 
In downloads/nextcloud/version.php is:
> $OC_Version = array(9,1,2,2);
> $OC_VersionString = '10.0.2';

**Comment by MorrisJobke** [comment]
> So I have version 10.0.0.1 and it tries to update to 9.1.2.2? Heh.. after looking into version.php I see it.. but then you should show to user OC_VersionString I think :)

This is a bit confusing: the internal version number for Nextcloud 10.0 is 9.1 (9.1.2.2 is 10.0.2.2).



> In backups is folder: nextcloud-9.1.1.5
> In backups/nextcloud-9.1.1.5/version.php is:

Looks good.



> In downloads is folder: nextcloud
> In downloads/nextcloud/version.php is:

Looks good.



> In step file is:
> 
> {"state":"end","step":6}

Fine.

Could you open the updater again in the web UI (or if this still is open click "retry" button)? There are some steps if you reopen the updater for security reasons. Then click continue button there.

**Comment by ronnicek** [comment]
In updater there was a button "Continue upgrade" (or someting like that) and update finish properly.

Do you have an idea what was the problem? I think we can close this issue for now :)

**Comment by MorrisJobke** [comment]
> Do you have an idea what was the problem? I think we can close this issue for now :)

Sadly not. Maybe a connection issue. I will try to add more details to the log and the web UI to make it more obvious what happened.

> In updater there was a button "Continue upgrade" (or someting like that) and update finish properly.

Nice 👍

**Comment by MorrisJobke** [comment]
@ronnicek Hey - we just want to send you a t-shirt for this feedback - could you send me your address to my email address in my github profile? ;)

**Comment by MorrisJobke** [comment]
🎉

**Comment by ronnicek** [comment]
Wow, thanks! Done :-) 👍 🎆
