### ISSUE TITLE
Checking the permissions of the Nextcloud root

### ISSUE THREAD

**Issue by crumbking** [nextcloud/updater#66]
followed the docs for Setting Strong Directory Permissions

**Comment by tflidd** [comment]
The docs state clearly that you have to change the permissions during upgrades:
https://docs.nextcloud.com/server/9.0/admin_manual/maintenance/update.html#set-updating-permissions-label

Can we add some checks for this recommended setup and provide the required steps to fix it or link to the documentation?

**Comment by JSoko** [comment]
IMHO at least it should be mentioned on the Error message that 
sudo chown -R www-data:www-data /var/www/nextcloud
could solve the problem..

**Comment by MorrisJobke** [comment]
> IMHO at least it should be mentioned on the Error message that
> sudo chown -R www-data:www-data /var/www/nextcloud
> could solve the problem..

Makes sense 👍

**Comment by robertoschwald** [comment]
This issue is open since 2016. Hope this simple check is implemented, soon.

**Comment by joshtrichards** [comment]
This hasn't been relevant since 2017. See nextcloud/documentation#431. Follows-ups are probably best taken to nextcloud/documentation#1353. Closing here since the Updater is no longer impacted by this.
