### ISSUE TITLE
Stuck on step 4 (10.0.1 -> 10.0.0.2) 

### ISSUE THREAD

**Issue by SunboX** [nextcloud/updater#67]
## Create backup

```
Parsing response failed. <html> <head><title>504 Gateway Time-out</title></head> <body bgcolor="white"> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.6.2</center> </body> </html>
```

![bildschirmfoto 2016-12-11 um 11 44 15](https://cloud.githubusercontent.com/assets/83344/21079698/04fd9b8e-bf9a-11e6-8273-32312d2e0dfb.png)

**Comment by LukasReschke** [comment]
This seems to be caused by a reverse proxy or something like that. A timeout is encountered and the response couldn't get parsed. Not much that we can do - you may want to try the PHAR updater or increase the timeouts.

**Comment by SunboX** [comment]
Thanks for the tip with the PHAR updater, it worked. 👍 

![wp_ss_20161212_0004](https://cloud.githubusercontent.com/assets/83344/21098311/e6894a3e-c068-11e6-8104-f817c2b19dc5.png)

**Comment by jospoortvliet** [comment]
@SunboX we express awe and respect at your use of a mobile phone to update your Nextcloud server and appreciate your confidence. :clap: :godmode: :bowing_man: :bowing_woman:
