### ISSUE TITLE
Add official support for controlled roll outs

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/updater#69]
We should have a config switch that allows us to define in a percentage how many instances should receive the update already. The client update server has this already and we should also have it for the server. 

This way we could for example let's say roll out Nextcloud 11 via the updater already to 5% of our users a day and if we encounter issues not all users would encounter them. Which means we could stop serving the 11 update and ship the minor releases instead.

Ideas on how to implement this are implemented :)

cc @karlitschek @MorrisJobke FYI

**Comment by LukasReschke** [comment]
Ah should probably have filed this under https://github.com/nextcloud/updater_server but since it's related anyhow let's track it here for now to reduce the notification spam :)

**Comment by LukasReschke** [comment]
@nickvergessen had a nice idea and discussed it with me in IRC. I'll create a PR for review :)

**Comment by karlitschek** [comment]
awesome idea. i wanted to have something like this for years :-)
