### ISSUE TITLE
after upgrade theme setting is gone

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/updater#71]
After upgrading from 10.0.1 to 10.0.2 theme setting in `config.php` has been set to `  'theme' => '',`

**Comment by jancborchardt** [comment]
I believe this is done because themes can break Nextcloud. However it should not be done for a minor update or even patch update, right? cc @MorrisJobke @LukasReschke @juliushaertl

**Comment by juliushaertl** [comment]
There was some notice in the documentation, but I can't find it at the moment, about themes being disabled on updates to avoid breaking instances.

But yes, as @jancborchardt said, we should keep them activated on minor updates.

**Comment by MorrisJobke** [comment]
We had in the past many issues with themes that destroyed the update page and caused update failures. So we disable this on all updates. No matter if a minor or a major. But maybe we could reenable this after the update.

This is an issue of the server component. @mcnesium Could you please open this in the server issue tracker: https://github.com/nextcloud/server/issues

Thanks :)
