### ISSUE TITLE
Link to forum redirects to ownCloud

### ISSUE THREAD

**Issue by enoch85** [nextcloud/updater#72]
Just tried to update between major versions, and the updater app linked to [this](https://forum.owncloud.org/viewtopic.php?f=17&t=32087) post on ownCloud. 

Looked where to change it but didn't find it, so here you go with an issue instead of a PR.

![screenshot from 2016-12-22 21-28-18](https://cloud.githubusercontent.com/assets/4511254/21439327/ad4a89cc-c88d-11e6-9fbb-af8820dbf10b.png)

"Check our forum post"

**Comment by MorrisJobke** [comment]
This is in the server part - maybe @nickvergessen or @lukasreschke want to fix this 🙈

**Comment by nickvergessen** [comment]
Fixed in https://github.com/nextcloud/server/issues/2933
