### ISSUE TITLE
Warn users of large setups before you replace the code

### ISSUE THREAD

**Issue by tflidd** [nextcloud/updater#73]
#### Current Situation:
User has a large setup with more than 50 users.

1. He start the updater app
2. User gets message `Please use the command line updater because you have a big instance.`

On shared hosting some people are not able to run commands via terminal. In this case people can only disable the large-instance checks and hope that it works, or they migrate Nextcloud to a local setup for upgrade. Both options take some time. This is a frequent problem for users running Nextcloud on webhosting setups, e.g. https://help.nextcloud.com/t/update-mess-forced-to-us-command-line-how/7102

#### Improvement:
Warn users that they have a large setup and that it is preferred to run the upgrade process via terminal. Provide links to documentation. This gives people time to figure out a solution and continue using Nextcloud.

**Comment by MorrisJobke** [comment]
I don't see a problem with big instances here. The updater here only replaces files. The size of the instance has no impact on the time this takes. Only the web based migration could have problems. And there this check is already enabled and you need to do the CLI way of updating (aka running the migration).

**Comment by tflidd** [comment]
Some users can't do upgrades via CLI commands. The updater replaces the code and then they can't use NC until they figured out what to do (e.g. manually copy the old code back which is not very user friendly).

**Comment by derbronko** [comment]
I really recommend to not force cloud administrators to update the nc with cli.
What will happen if there is a admin that is not able to run this? 
Will he stay locked out for ever?

**Comment by chrisk2204** [comment]
Hey Guys,

I have that problem. NC tells me, that I have to use the CLI, because of my huge installation. Funny! I am on a shared host, can't connect via SSH and have only 12 Users. This isn't that much, isn't it? 
I have one local User and eleven LDAP users. What to do? I would appreciate to be warned before send me into that death struggle.

**Comment by joshtrichards** [comment]
Fixed in nextcloud/server#4805
Fixed in nextcloud/server#4804
