### ISSUE TITLE
updater uses lots of System Resources

### ISSUE THREAD

**Issue by holzfelix** [nextcloud/updater#86]
The updater app for windows uses too much resourses. Is there a way to reduce the amount of system resources? 

I'm using windows 10 64bit professional, i7 6200 and 16GB ram. When app is in sync mode the whole system is unusable. 

Already tried to reinstall the app.

**Comment by MorrisJobke** [comment]
This is the updater and not the client. Please open a ticket in https://github.com/nextcloud/client_theming/issues

And maybe attach some screenshots of the system monitoring tool to see if it uses CPU, RAM, etc ... 

cc @rullzer maybe he already has an idea what is happening here.
