### ISSUE TITLE
PHP7.1 guzzle error "Cannot use lexical variable $eventName as a parameter name"

### ISSUE THREAD

**Issue by azrdev** [nextcloud/updater#87]
As pointed out in [1] and [2], the updater logs this error when I try to use it on PHP7.1:
~~~
Error PHP Cannot use lexical variable $eventName as a parameter name at /path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/Event/Emitter.php#48
~~~
This seems to be https://github.com/guzzle/guzzle/issues/1634

[1] <https://help.nextcloud.com/t/protect-your-privacy-time-to-upgrade-to-nextcloud-11/8516/2>
[2] <https://help.nextcloud.com/t/does-nextcloud-11-support-php-7-1/6241/3>

**Comment by gopalsharma01** [comment]
I think, you are using Guzzle 5.3 on PHP 7.1, so please use below command in terminal.

composer require "guzzlehttp/guzzle:^6.0"

It's working for me.

**Comment by MorrisJobke** [comment]
Guzzle was updated to 6.3 https://github.com/nextcloud/3rdparty/commit/ffb6a3a10985ae6dca121200760a78b5a75aa5d5#diff-1e2e2790c9f09273667cec05a1879ef8
