### ISSUE TITLE
JSON response without Content-Type

### ISSUE THREAD

**Issue by dlichtenberger** [nextcloud/updater#88]
The JSON responses to POST requests lacks a Content-Type header. This is an issue if Nextcloud is running behind Apache's mod_proxy_html, which corrupts the response by wrapping it in \<html>/\<body> tags. For me the issue was fixed by adding

```php
header("Content-Type: application/json");
```

before sending the response to a POST request.

**Comment by MorrisJobke** [comment]
@dlichtenberger Could I ask you to make this change as a pull request? That would be super nice :)

**Comment by joshtrichards** [comment]
This will likely address all the "Parsing response failed" experiences that make troubleshooting installations (and analyzing bug reports) more challenging than necessary.

e.g. https://github.com/nextcloud/updater/issues?q=is%3Aissue+is%3Aopen+%22parsing+response+failed%22
