### ISSUE TITLE
filesystem user used in update

### ISSUE THREAD

**Issue by fireba11** [nextcloud/updater#89]
Hi,
I got nextcloud running in a web in ISPconfig (a management tool for shared webs) where the web used is supposed to have file permissions like web12:client3. That works with just about everything else i troed (including things like Wordpress auto-updater) but for some reason nextcloud insists on all files being owned by www-data:www-data for the updater to work.
The special users are a security feature to properly seperate the webs, so i think the updater should learn to work with setups like that since they are rather common too.
Note: If i change everything back to the limited user nextcloud itself is working fine, it's just the updater check complaining.

**Comment by MorrisJobke** [comment]
> Note: If i change everything back to the limited user nextcloud itself is working fine, it's just the updater check complaining.

Yep, because Nextcloud itself doesn't overwrite the code files. Is the webserver user allowed to overwrite the files? Because that is the reason for this check.

**Comment by MorrisJobke** [comment]
Sadly we can't do much here. If the webserver user can't update the files an update via web is not possible.

**Comment by fireba11** [comment]
nope, the updater checks for the wrong user. nexcloud can overwrite the files, but the updater thinks it's wrong
