### ISSUE TITLE
Upgrade from 10.0.3 to 11.0.2 failed with InvalidArgumentException

### ISSUE THREAD

**Issue by jomat** [nextcloud/updater#91]
Hello,

upgrading just failed:

{"reqId":"redacted","remoteAddr":"","app":"user_ldap","message":"uid for 'cn=system administrator-fd-admin,ou=people,dc=example,dc=com' must not be an empty string","level":3,"time":"2017-03-18T15:57:38+00:00","method":"--","url":"--","user":"--","version":"9.1.3.2"}

{"reqId":"redacted","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"uid must not be an empty string!\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User\\\/Manager.php(121): OCA\\\\User_LDAP\\\\User\\\\User->__construct('', 'cn=system admin...', Object(OCA\\\\User_LDAP\\\\Access), Object(OC\\\\AllConfig), Object(OCA\\\\User_LDAP\\\\FilesystemHelper), Object(OCP\\\\Image), Object(OCA\\\\User_LDAP\\\\LogWrapper), Object(OC\\\\AvatarManager), Object(OC\\\\User\\\\Manager))\\n#1 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User\\\/Manager.php(212): OCA\\\\User_LDAP\\\\User\\\\Manager->createAndCache('cn=system admin...', '')\\n#2 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User\\\/Manager.php(238): OCA\\\\User_LDAP\\\\User\\\\Manager->createInstancyByUserName('')\\n#3 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php(305): OCA\\\\User_LDAP\\\\User\\\\Manager->get('')\\n#4 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Manager.php(408): OCA\\\\User_LDAP\\\\User_LDAP->userExists('')\\n#5 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Migration\\\/ValueFixInsert.php(59): OC\\\\User\\\\Manager->callForSeenUsers(Object(Closure))\\n#6 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/lib\\\/private\\\/Repair.php(94): OCA\\\\DAV\\\\Migration\\\\ValueFixInsert->run(Object(OC\\\\Repair))\\n#7 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(1201): OC\\\\Repair->run()\\n#8 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/app.php(1136): OC_App::executeRepairSteps('dav', Array)\\n#9 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(359): OC_App::updateApp('dav')\\n#10 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(245): OC\\\\Updater->doAppUpgrade()\\n#11 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(124): OC\\\\Updater->doUpgrade('11.0.2.7', '9.1.3.2')\\n#12 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/core\\\/Command\\\/Upgrade.php(261): OC\\\\Updater->upgrade()\\n#13 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(256): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#14 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(818): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#15 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(186): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#16 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(117): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#17 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(169): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#18 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/console.php(90): OC\\\\Console\\\\Application->run()\\n#19 \\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/occ(11): require_once('\\\/var\\\/customers\\\/...')\\n#20 {main}\",\"File\":\"\\\/var\\\/customers\\\/webs\\\/owncloud.example.org\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User\\\/User.php\",\"Line\":121}","level":3,"time":"2017-03-18T15:57:38+00:00","method":"--","url":"--","user":"--","version":"9.1.3.2"}

But the user looks like:
```
% ldapsearch -x -b 'uid=fd-admin,ou=people,dc=example,dc=com'           
# extended LDIF
#
# LDAPv3
# base <uid=fd-admin,ou=people,dc=example,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# fd-admin, people, example.com
dn: uid=fd-admin,ou=people,dc=example,dc=com
objectClass: top
objectClass: person
objectClass: gosaAccount
objectClass: organizationalPerson
objectClass: inetOrgPerson
uid: fd-admin
sn: Administrator
givenName: System
cn: System Administrator

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

The problem was caused by a strange record in the ldap_user_mapping table, no idea how it came there, the installation is quite old:
```
cn=system administrator-fd-admin,ou=people,dc=example,dc=com |               | fd-admin
```
After editing this record, the update finished without further errors:
```
owncloud=# update oc_ldap_user_mapping set owncloud_name = 'fd-admin' where directory_uuid = 'fd-admin';
```

**Comment by MorrisJobke** [comment]
Sorry for the late reply, but this is a problem with the server component (executing the migration steps) and not the updater (which only replaces the old files with the new ones).

Could I ask you to open this in the server repo? https://github.com/nextcloud/server

Thanks

cc @blizzz anyway for this LDAP related thing.
