### ISSUE TITLE
"Check for expected files" fails with custom data directory

### ISSUE THREAD

**Issue by vanMacG** [nextcloud/updater#92]
I'm migrating from owncloud to nextcloud while experiencing the following problem with the updater.
I'm on nextcloud 9.0.57 now and the updater tries to update to 10.0.3 put fails at the 1st step "Check for expected files":
```
The following extra files have been found:
data_ufdruqd6b2
```
I added a string to the default data folder, and specified it in the config.php.
This is a bit like a duplicate of https://github.com/owncloud/core/pull/22756 which was the same problem but in the integrity checker in core.

**Comment by TraceyC77** [comment]
This is affecting my installation as well. I have a custom data directory that I have specified in config.php

> Nextcloud Updater - version: 1.0.3
> Current version is 11.0.3.
> Update to Nextcloud 11.0.4 available. (channel: "production")
...
> [✘] Check for expected files failed
> The following extra files have been found:
>     .htxcpwl3z2vaif.data

I get this error whether I use the web based updater or updater.phar

**Comment by kesselb** [comment]
Closing in favor of https://github.com/nextcloud/updater/issues/201

(this report is older but has fewer comments, please give the other issue a thumbs up)
