### ISSUE TITLE
Check user count before update

### ISSUE THREAD

**Issue by cal940** [nextcloud/updater#94]
If you have more than 50 users configured, you have to update manually.

- aspected: check user count before update and ask the user for permission to start a manual update.
- actual: the update starts and the user gets a message after that.

Please consider that there are users they don't have unlimited terminal access. These users are forced to reinstall nextcloud.

**Comment by MorrisJobke** [comment]
It's now possible to run the web updater anyways: https://github.com/nextcloud/server/pull/4805

But I will add a warning to the updater button.

**Comment by MorrisJobke** [comment]
Opened as ticket in the server. https://github.com/nextcloud/server/issues/5019
